### ISSUE TITLE
DeviceStateHolder leaks Receivers not unregistered

### ISSUE THREAD

**Issue by Catfriend1** [syncthing/syncthing-android#1120]
Reproducer
Open Syncthing app
go to settings
enable always run syncthing on background
enable run on wifi
disable run on wifi
go back to home screen
press back button
from home screen press syncthing is running notification
go to settings
disable always run syncthing on background
go to MainActivity
exit syncthing app

![image](https://user-images.githubusercontent.com/16361913/40930670-98b23f5a-6828-11e8-8d66-c2887d9384b9.png)

    Report valid for: https://github.com/syncthing/syncthing-android/commit/165c136beae31514d701791c9f654b2568338f46
    App Version: 0.10.10+
    Syncthing Version: v0.14.47
    Android Version: Android 7.1.2

**Comment by Catfriend1** [comment]
At commit https://github.com/syncthing/syncthing-android/pull/1119/commits/c32370d024e8292b13e852a08d47698003751d7d, lifecycling of the receivers was implementing doing a null check before calling unregisterReceiver() and nulling if it was called.
The log seems to be clean but stress testing changing the run conditions in settings  UI crashes with an IllegalArgumentException.
![image](https://user-images.githubusercontent.com/16361913/40931011-b628c6b6-6829-11e8-8410-041f43d149a9.png)

**Comment by Catfriend1** [comment]
At commit https://github.com/syncthing/syncthing-android/pull/1119/commits/0c32f26dc7fd44bcbef45d1006312fbff496a097 I implemented the receiver lifecycle (create, destroy if registered) in a separate class "ReceiverManager". This simplifies code, e.g. if onPreferencesChange() event is fired in DeviceStateHolder. Still, null checking does not suffice according to https://stackoverflow.com/a/3568906 . Storing the result of registerReceiver might be null when the receiver is unregistered shortly after registration (as its not complete). Unfortunately, android does not provide a function "isReceiverRegistered" and checking for null also doesn't suffice.

Best way to solve this I found is mentioned in the SO article by managing the receivers lifecycle in ReceiverManager and storing every registered receiver in a list. See https://github.com/syncthing/syncthing-android/pull/1119/commits/68fd7aadb925c272fcc66a0ccee133f0f9723a7e

I improved the SO implementation and made the class parts static. If they aren't static, lint warnings come up and the code doesn't work. Verified as a working solution I got a clean log like shown above and the "IllegalArgumentException e" never occured anymore.

Receiver registration (as intended by the parent code) occurs only one time per receiver and is properly unregistered without leaks. I verified this to work when syncthing runs foregrounded and when it runs always in the  background.

**Comment by Catfriend1** [comment]
With the ReceiverManager in place as referenced above, the leak is forever fixed, even when stress testing the UI and run conditions:
![image](https://user-images.githubusercontent.com/16361913/40933147-ec36a9d8-6830-11e8-8a3b-0a0db91e8831.png)

**Comment by Catfriend1** [comment]
Also related before the problem got fixed with PR #1119 

06-03 12:28:43.068 V/SyncthingService(27728): onDestroy
06-03 12:28:43.069 I/SyncthingService(27728): Shutting down syncthing binary immediately
06-03 12:28:43.069 I/SyncthingService(27728): Shutting down background service
06-03 12:28:43.069 D/EventProcessor(27728): Shutdown event processor.
06-03 12:28:43.072 V/LASTMESSAGEg(5506): Received last update Datenschutz aktiv - Syncthing hat keinen Zugriff auf persönliche Daten
06-03 12:28:43.084 V/DeviceStateHolder(27728): Shutting down
06-03 12:28:43.099 V/LASTMESSAGEg(5506): Received last update Syncthing läuft - 
06-03 12:28:43.127 V/SyncthingRunnable(27728): getSyncthingPIDs: Found process PID [27794]
06-03 12:28:43.141 I/SyncthingNativeCode(27728): [EI7WS] INFO: Exiting
06-03 12:28:43.145 E/ActivityThread(27728): Service com.nutomic.syncthingandroid.service.SyncthingService has leaked IntentReceiver com.nutomic.syncthingandroid.receiver.PowerSaveModeChangedReceiver@b53030 that was originally registered here. Are you missing a call to unregisterReceiver()?
06-03 12:28:43.145 E/ActivityThread(27728): android.app.IntentReceiverLeaked: Service com.nutomic.syncthingandroid.service.SyncthingService has leaked IntentReceiver com.nutomic.syncthingandroid.receiver.PowerSaveModeChangedReceiver@b53030 that was originally registered here. Are you missing a call to unregisterReceiver()?
06-03 12:28:43.145 E/ActivityThread(27728): 	at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1159)
06-03 12:28:43.145 E/ActivityThread(27728): 	at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:946)
06-03 12:28:43.145 E/ActivityThread(27728): 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1302)
06-03 12:28:43.145 E/ActivityThread(27728): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1282)
06-03 12:28:43.145 E/ActivityThread(27728): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1276)
06-03 12:28:43.145 E/ActivityThread(27728): 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:586)
06-03 12:28:43.145 E/ActivityThread(27728): 	at com.nutomic.syncthingandroid.service.DeviceStateHolder.updateReceivers(DeviceStateHolder.java:153)
06-03 12:28:43.145 E/ActivityThread(27728): 	at com.nutomic.syncthingandroid.service.DeviceStateHolder.<init>(DeviceStateHolder.java:99)
06-03 12:28:43.145 E/ActivityThread(27728): 	at com.nutomic.syncthingandroid.service.SyncthingService.onStartCommand(SyncthingService.java:162)
06-03 12:28:43.145 E/ActivityThread(27728): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3351)
06-03 12:28:43.145 E/ActivityThread(27728): 	at android.app.ActivityThread.-wrap21(ActivityThread.java)
06-03 12:28:43.145 E/ActivityThread(27728): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1601)
06-03 12:28:43.145 E/ActivityThread(27728): 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-03 12:28:43.145 E/ActivityThread(27728): 	at android.os.Looper.loop(Looper.java:154)
06-03 12:28:43.145 E/ActivityThread(27728): 	at android.app.ActivityThread.main(ActivityThread.java:6186)
06-03 12:28:43.145 E/ActivityThread(27728): 	at java.lang.reflect.Method.invoke(Native Method)
06-03 12:28:43.145 E/ActivityThread(27728): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
06-03 12:28:43.145 E/ActivityThread(27728): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
06-03 12:28:43.147 E/StrictMode(27728): null
06-03 12:28:43.147 E/StrictMode(27728): android.app.IntentReceiverLeaked: Service com.nutomic.syncthingandroid.service.SyncthingService has leaked IntentReceiver com.nutomic.syncthingandroid.receiver.PowerSaveModeChangedReceiver@b53030 that was originally registered here. Are you missing a call to unregisterReceiver()?
06-03 12:28:43.147 E/StrictMode(27728): 	at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1159)
06-03 12:28:43.147 E/StrictMode(27728): 	at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:946)
06-03 12:28:43.147 E/StrictMode(27728): 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1302)
06-03 12:28:43.147 E/StrictMode(27728): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1282)
06-03 12:28:43.147 E/StrictMode(27728): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1276)
06-03 12:28:43.147 E/StrictMode(27728): 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:586)
06-03 12:28:43.147 E/StrictMode(27728): 	at com.nutomic.syncthingandroid.service.DeviceStateHolder.updateReceivers(DeviceStateHolder.java:153)
06-03 12:28:43.147 E/StrictMode(27728): 	at com.nutomic.syncthingandroid.service.DeviceStateHolder.<init>(DeviceStateHolder.java:99)
06-03 12:28:43.147 E/StrictMode(27728): 	at com.nutomic.syncthingandroid.service.SyncthingService.onStartCommand(SyncthingService.java:162)
06-03 12:28:43.147 E/StrictMode(27728): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3351)
06-03 12:28:43.147 E/StrictMode(27728): 	at android.app.ActivityThread.-wrap21(ActivityThread.java)
06-03 12:28:43.147 E/StrictMode(27728): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1601)
06-03 12:28:43.147 E/StrictMode(27728): 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-03 12:28:43.147 E/StrictMode(27728): 	at android.os.Looper.loop(Looper.java:154)
06-03 12:28:43.147 E/StrictMode(27728): 	at android.app.ActivityThread.main(ActivityThread.java:6186)
06-03 12:28:43.147 E/StrictMode(27728): 	at java.lang.reflect.Method.invoke(Native Method)
06-03 12:28:43.147 E/StrictMode(27728): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
06-03 12:28:43.147 E/StrictMode(27728): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
06-03 12:28:43.156 E/Volley  (27728): [876] BasicNetwork.performRequest: Unexpected response code 200 for https://127.0.0.1:8384/rest/events?since=7&limit=0
06-03 12:28:43.158 I/SyncthingRunnable(27728): Syncthing exited with code 0
06-03 12:28:43.203 I/GoogleInputMethod(4180): onFinishInput() : Dummy InputConnection bound



> 06-03 12:26:44.650 I/ActivityManager(2071): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.nutomic.syncthingandroid.debug/com.nutomic.syncthingandroid.activities.FirstStartActivity (has extras)} from uid 10022 on display 0
06-03 12:26:44.748 V/FirstStartActivity(27728): startService SyncthingService
06-03 12:26:44.756 V/LASTMESSAGEg(5506): Received last update Datenschutz aktiv - Syncthing hat keinen Zugriff auf persönliche Daten
06-03 12:26:44.760 I/ActivityManager(2071): START u0 {cmp=com.nutomic.syncthingandroid.debug/com.nutomic.syncthingandroid.activities.MainActivity (has extras)} from uid 10265 on display 0
06-03 12:26:44.790 V/SyncthingService(27728): onStartCommand
06-03 12:26:44.790 V/DeviceStateHolder(27728): Created new instance
06-03 12:26:44.790 I/DeviceStateHolder(27728): Stopped listening to network state changes
06-03 12:26:44.790 I/DeviceStateHolder(27728): Stopped listening to battery state changes
06-03 12:26:44.790 I/DeviceStateHolder(27728): Listening to power saving changes
06-03 12:26:44.876 V/DeviceStateHolder(27728): State updated, allowed network connection: false, charging: false, power saving: false
06-03 12:26:44.877 V/DeviceStateHolder(27728): State updated, allowed network connection: false, charging: false, power saving: false
06-03 12:26:44.878 I/DeviceStateHolder(27728): updateShouldRunDecision: Sending state change from false to true
06-03 12:26:44.897 V/LASTMESSAGEg(5506): Received last update Syncthing läuft - 
06-03 12:26:44.921 W/PackageManager(4193): Failure retrieving resources for com.pluscubed.matlog: Drawable com.pluscubed.matlog:mipmap/ic_launcher with resource ID #0x7f0d0000
06-03 12:26:44.996 I/thermanager(460): "cpu-a57" set to level 6
06-03 12:26:45.127 V/ApiRequest(27728): Performing request to https://127.0.0.1:8384/rest/system/status
06-03 12:26:45.127 V/ApiRequest(27728): Performing request to https://127.0.0.1:8384/rest/system/version
06-03 12:26:45.128 V/ApiRequest(27728): Performing request to https://127.0.0.1:8384/rest/system/connections
06-03 12:26:45.128 V/ApiRequest(27728): Performing request to https://127.0.0.1:8384/rest/system/status
06-03 12:26:45.196 I/GoogleInputMethod(4180): onFinishInput() : Dummy InputConnection bound

**Comment by AudriusButkevicius** [comment]
This still doesn't look right, as multiple registrations happen before deregistrations, which implies multiple instances get created?

Why can't you just lock around the variable?:

**Comment by Catfriend1** [comment]
Ahem... I dont think we need to lock as the registrations and deregs can only occur "in proper order" on create, on prefchange and on shutdown. Verify by running it and youll get the expected result that every receiver registered is properly released forever or until it is registered again. (Filter on DeviceStateHolder and ReceiverManager)

**Comment by AudriusButkevicius** [comment]
Why would there be multiple creates if it happens in proper order?

**Comment by Catfriend1** [comment]
Because we can have up to three different receivers registered and taken care of ReceiverManager class (power, network, battery) which ones are registered depends on run condition prefs set.

**Comment by AudriusButkevicius** [comment]
ah ok, the class names are truncated.
