### ISSUE TITLE
syncing files from Android with special caracters

### ISSUE THREAD

**Issue by schuft69** [syncthing/syncthing-android#192]
Some apps generate pictures named like (eg. Handgouts when taking a picture with it):

`IMG_20140825_162547:nopm:.jpg`

When I try to sync this to my windows-pc it does not like the ":" in the filename and I'am not able to sync this.

`File name "Camera/IMG_20140825_162547:nopm:.jpg" contains invalid characters; marked as invalid.`

I would recomment to add an option to the android app, that is called "rename special caracters to '_' befor sync" to work around this (windows)-issue.
Thats the way btsync is doing it.

Regards,
schuft69

**Comment by Nutomic** [comment]
syncthing/syncthing#430

**Comment by Zillode** [comment]
Fixed in upstream https://github.com/syncthing/syncthing/commit/8311162be31d5f3e5fb4bd4c21ddf5e7356802cf

**Comment by michaelarnauts** [comment]
I still see these messages on my windows host (syncing from my linux server) on v0.11.1.

-> 19:43:10: File name "IMG_20150326_173306:nopm:.jpg" contains invalid characters; marked as invalid.

**Comment by Zillode** [comment]
Sorry upstream fixed the NFC/NFD UTF8 encoding. A colon (`:`) is a perfectly valid character, thus Syncthing will not modify it.
I don't see how we can resolve this as we will not modify your filenames...

**Comment by Zillode** [comment]
@schuft69, is this option available on the android or the desktop client?

**Comment by schuft69** [comment]
It is available (but not configurable) on the Windows-Client.
