### ISSUE TITLE
Syncthing binary crashed with error code 11 after update to 0.7.5

### ISSUE THREAD

**Issue by pascalfree** [syncthing/syncthing-android#515]
Hi

Since I updated to Syncthing for Android 0.7.5 the app is stuck on "loading".
This is on an HTC One V with Android 4.0.3

This is the log, when I force close syncthing and it restarts itself:

    2015-12-12 03:32:08,INFORMATION,ActivityManager,Android System,Displayed com.nutomic.syncthingandroid/.activities.MainActivity: +1s357ms
    2015-12-12 03:32:19,INFORMATION,dalvikvm,Syncthing,Could not find method android.net.ConnectivityManager.isActiveNetworkMetered, referenced from method com.nutomic.syncthingandroid.syncthing.DeviceStateHolder.<init>
    2015-12-12 03:32:19,INFORMATION,SyncthingService,Syncthing,Web GUI will be available at https://127.0.0.1:8384
    2015-12-12 03:32:19,INFORMATION,SyncthingService,Syncthing,Starting syncthing according to current state and preferences
    2015-12-12 03:32:20,INFORMATION,DEBUG,/system/bin/debuggerd,pid: 27376, tid: 27376  >>> /data/data/com.nutomic.syncthingandroid/lib/libsyncthing.so <<<

    2015-12-12 03:32:20,INFORMATION,DEBUG,/system/bin/debuggerd,40040000-408d7000 /data/data/com.nutomic.syncthingandroid/lib/libsyncthing.so

    2015-12-12 03:32:20,INFORMATION,System,Syncthing,libcore.io.ErrnoException: kill failed: ESRCH (No such process)
	at libcore.io.Posix.kill(Native Method)
	at libcore.io.ForwardingOs.kill(ForwardingOs.java:77)
	at java.lang.ProcessManager$ProcessImpl.destroy(ProcessManager.java:257)
	at com.nutomic.syncthingandroid.syncthing.SyncthingRunnable.run(SyncthingRunnable.java:136)
	at java.lang.Thread.run(Thread.java:864)

    2015-12-12 03:32:20,ERROR,SyncthingNativeCode,Syncthing,Syncthing binary crashed with error code 11
    2015-12-12 03:32:20,WARNING,SyncthingNativeCode,Syncthing,sh: <stdin>[1]: grep: not found
    2015-12-12 03:32:21,WARNING,SyncthingNativeCode,Syncthing,usage: ionice <pid> [none|rt|be|idle] [prio]
    2015-12-12 03:32:21,INFORMATION,SyncthingRunnableIoNice,Syncthing,ionice performed on libsyncthing.so
    2015-12-12 03:32:21,INFORMATION,System,Syncthing,libcore.io.ErrnoException: kill failed: ESRCH (No such process)
	at libcore.io.Posix.kill(Native Method)
	at libcore.io.ForwardingOs.kill(ForwardingOs.java:77)
	at java.lang.ProcessManager$ProcessImpl.destroy(ProcessManager.java:257)
	at com.nutomic.syncthingandroid.syncthing.SyncthingRunnable$1.run(SyncthingRunnable.java:183)

    2015-12-12 03:32:21,ERROR,SyncthingRunnableIoNice,Syncthing,Failed to set ionice 1

It says "Syncthing binary crashed with error code 11", but I could not find anything about this that code.

Is there anything I can do?

Sidenote: I can not access my config.xml because the device is not rooted, and the app is stuck on loading. Would be nice if one could still export the config even if the binary crashes.

Thank you

**Comment by gerroon** [comment]
I am getting more stucks and laoding forevers with the 0.7.x branc. I do not remeber this being as bad with the 0.6x versions. 

I use this on various android models but most of them are Android 4xs

**Comment by capi** [comment]
The following log line is interesting:
    2015-12-12 03:32:19,INFORMATION,dalvikvm,Syncthing,Could not find method android.net.ConnectivityManager.isActiveNetworkMetered, referenced from method com.nutomic.syncthingandroid.syncthing.DeviceStateHolder.<init>

It's due to the check that's for metered WiFis, which has been introduced in API level 16 (4.1), you are on 16. Still, this code block is behind a version guard, so I hope the message is just information by dalvik and not a crash information.

Also very alarming I find this:
    2015-12-12 03:32:20,WARNING,SyncthingNativeCode,Syncthing,sh: <stdin>[1]: grep: not found

This means, `grep` is not available on this Android version, it is used by syncthing-android to find the native code to kill, though.

Maybe there is an old instance of Syncthing running which got not killed due to this and it hangs in loading because it failed in killing the old process?

**Comment by pascalfree** [comment]
Restarting the phone didn't help (I assume this would close all old syncthing instances).
Any Idea, what the error code 11 is about?
I would check the syncthing source, but I don't know what to look for, I never worked with go.

Am 13. Dezember 2015 22:10:46 MEZ, schrieb Martin Carpella <notifications@github.com>:

**Comment by Nutomic** [comment]
@calmh @AudriusButkevicius Any idea about the error code 11?

@Zillode I guess grep requires Busybox installed. I think we should handle that in Java instead.

**Comment by AudriusButkevicius** [comment]
11 is segfault. Probably something with the way it's compiled as we moved to cgo?

**Comment by Zillode** [comment]
@Nutomic sure but no harm is caused because of this:)

Maybe we should build a release without cgo to test this?

**Comment by Nutomic** [comment]
@Zillode Couldn't it be a problem because kill doesn't work? And go ahead the the build, I don't really know how to do that :p

**Comment by gerroon** [comment]
I salvaged from logcat. It is a bit hard to produce this error because sometijmes it takes many hours until it crashes and never recovers. And sometimes The ui will be unresposive other times the ui will responsive but no syncthing binary or web server lying beneath.

I/ActivityManager( 1590): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.nutomic.syncthingandroid/.activities.MainActivity} from pid 24380
I/ActivityManager( 1590): Start proc com.nutomic.syncthingandroid for activity com.nutomic.syncthingandroid/.activities.MainActivity: pid=24438 uid=10357 gids={50357, 1028, 1015, 3003}
I/ActivityManager( 1590): START u0 {cmp=com.nutomic.syncthingandroid/.activities.MainActivity bnds=[64,1408][1024,1536]} from pid -1
W/ActivityManager( 1590): startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { cmp=com.nutomic.syncthingandroid/.activities.MainActivity bnds=[64,1408][1024,1536] }
I/ActivityManager( 1590): START u0 {cmp=com.nutomic.syncthingandroid/.activities.MainActivity bnds=[64,2100][1024,2228]} from pid -1
W/ActivityManager( 1590): startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { cmp=com.nutomic.syncthingandroid/.activities.MainActivity bnds=[64,2100][1024,2228] }
I/ActivityManager( 1590): START u0 {act=folder_settings_fragment cmp=com.nutomic.syncthingandroid/.activities.SettingsActivity (has extras)} from pid 24438
I/ActivityManager( 1590): Killing 24438:com.nutomic.syncthingandroid/u0a357 (adj 16): remove task
W/ActivityManager( 1590): Scheduling restart of crashed service com.nutomic.syncthingandroid/.syncthing.SyncthingService in 1000ms
I/ActivityManager( 1590): Start proc com.nutomic.syncthingandroid for service com.nutomic.syncthingandroid/.syncthing.SyncthingService: pid=5709 uid=10357 gids={50357, 1028, 1015, 3003}
I/ActivityManager( 1590): Process com.nutomic.syncthingandroid (pid 5709) has died.
W/ActivityManager( 1590): Scheduling restart of crashed service com.nutomic.syncthingandroid/.syncthing.SyncthingService in 1000ms
F/ProcessStats( 1590): Starting service ServiceState{434bb6a0 com.nutomic.syncthingandroid.syncthing.SyncthingService pkg=com.nutomic.syncthingandroid proc=434bb6a0} without owner
I/ActivityManager( 1590): Start proc com.nutomic.syncthingandroid for service com.nutomic.syncthingandroid/.syncthing.SyncthingService: pid=14081 uid=10357 gids={50357, 1028, 1015, 3003}
I/ActivityManager( 1590): Process com.nutomic.syncthingandroid (pid 14081) has died.
W/ActivityManager( 1590): Scheduling restart of crashed service com.nutomic.syncthingandroid/.syncthing.SyncthingService in 1000ms
I/ActivityManager( 1590): Start proc com.nutomic.syncthingandroid for service com.nutomic.syncthingandroid/.syncthing.SyncthingService: pid=16143 uid=10357 gids={50357, 1028, 1015, 3003}
D/EventProcessor(16143): Sent local event broadcast com.nutomic.syncthingandroid.event.DEVICEDISCOVERED including 16 extra data items.
W/GetTask (16143): 	at com.nutomic.syncthingandroid.syncthing.GetTask.doInBackground(GetTask.java:77)
W/GetTask (16143): 	at com.nutomic.syncthingandroid.syncthing.GetTask.doInBackground(GetTask.java:28)
I/ActivityManager( 1590):   svcb  S    14583 kB: com.nutomic.syncthingandroid (16143) started-services
I/ActivityManager( 1590):   svcb  S    14395 kB: com.nutomic.syncthingandroid (16143) started-services
I/ActivityManager( 1590): START u0 {cmp=com.nutomic.syncthingandroid/.activities.MainActivity bnds=[64,1548][1024,1676]} from pid -1
W/ActivityManager( 1590): startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { cmp=com.nutomic.syncthingandroid/.activities.MainActivity bnds=[64,1548][1024,1676] }
W/GetTask (16143): 	at com.nutomic.syncthingandroid.syncthing.GetTask.doInBackground(GetTask.java:77)
W/GetTask (16143): 	at com.nutomic.syncthingandroid.syncthing.GetTask.doInBackground(GetTask.java:28)
W/GetTask (16143): 	at com.nutomic.syncthingandroid.syncthing.GetTask.doInBackground(GetTask.java:77)
W/GetTask (16143): 	at com.nutomic.syncthingandroid.syncthing.GetTask.doInBackground(GetTask.java:28)
I/ActivityManager( 1590): Displayed com.nutomic.syncthingandroid/.activities.MainActivity: +991ms
I/Timeline( 1590): Timeline: Activity_windows_visible id: ActivityRecord{4270b388 u0 com.nutomic.syncthingandroid/.activities.MainActivity t256} time:292760703
W/GetTask (16143): 	at com.nutomic.syncthingandroid.syncthing.GetTask.doInBackground(GetTask.java:77)

**Comment by Zillode** [comment]
Here's a non-cgo build: http://android.syncthing.net/view/Syncthing-Android/job/Syncthing-Android-Zillode/10/artifact/build/outputs/apk/syncthing-armeabi-debug.apk

**Comment by pascalfree** [comment]
Thank you, but no luck. The log looks similar (to my eyes at least):
[Log-2015-12-24-12.21.56.csv.txt](https://github.com/syncthing/syncthing-android/files/71316/Log-2015-12-24-12.21.56.csv.txt)

It says the configuration fails and that I should check the logs.

**Comment by gerroon** [comment]
I am getting frequent hidden crashes on Android Kitkat. What happens is that the ui works but the syncthing binary crashed. As a user I would never know that it happened until I open the web page which then shows that there is no webserver running which leads to the conclusion that the binary has crashed along the way. The thing is that I would not know when it crashed either.

**Comment by gerroon** [comment]
@Zillode 

It would have been nice if the package named properly, I now have 2 syncthings and I d onot know which one is which.

**Comment by Zillode** [comment]
@gerroon the custom build ends with .debug in the app information settings of Android.

**Comment by irregularisnotrandom** [comment]
0.7.5 has been constantly crashy on all of my devices. It looks like the syncthing binary silently crashes in the backgroud. Thos behavior is consisten across my android 4..5 devices.

**Comment by irregularisnotrandom** [comment]
Btw the latest arm binaryndoes not display this behavior on the same devices

**Comment by Zillode** [comment]
@irregularisnotrandom can you try the [debug build](http://android.syncthing.net/view/Syncthing-Android/job/Syncthing-Android-Zillode/10/artifact/build/outputs/apk/syncthing-armeabi-debug.apk)?

**Comment by bzzz2** [comment]
Tried debug build for @irregularisnotrandom . Still restarts. Log file added
[2016-01-09-15-34-30.txt](https://github.com/syncthing/syncthing-android/files/83643/2016-01-09-15-34-30.txt)

**Comment by Zillode** [comment]
@bzzz2 @irregularisnotrandom [This build](http://android.syncthing.net/view/Syncthing-Android/job/Syncthing-Android-Zillode/lastSuccessfulBuild/artifact/build/outputs/apk/syncthing-armeabi-debug.apk) is made with Go 1.6 beta, I hope it helps...

**Comment by irregularisnotrandom** [comment]
I still get crash. It does not stay running, somehow when i click on the tray st bar it restarts. 

I believe this is just before the crash

D/EventProcessor(21695): Sent local event broadcast com.nutomic.syncthingandroid.event.FOLDERCOMPLETION including 16 extra data items.
D/EventProcessor(21695): Sent local event broadcast com.nutomic.syncthingandroid.event.FOLDERCOMPLETION including 16 extra data items.
D/EventProcessor(21695): Sent local event broadcast com.nutomic.syncthingandroid.event.FOLDERCOMPLETION including 16 extra data items.
D/EventProcessor(21695): Sent local event broadcast com.nutomic.syncthingandroid.event.STATECHANGED including 12 extra data items.
D/EventProcessor(21695): Sent local event broadcast com.nutomic.syncthingandroid.event.FOLDERCOMPLETION including 16 extra data items.
D/EventProcessor(21695): Sent local event broadcast com.nutomic.syncthingandroid.event.FOLDERCOMPLETION including 16 extra data items.
D/EventProcessor(21695): Sent local event broadcast com.nutomic.syncthingandroid.event.FOLDERCOMPLETION including 16 extra data items.
D/EventProcessor(21695): Sent local event broadcast com.nutomic.syncthingandroid.event.FOLDERCOMPLETION including 16 extra data items.
D/EventProcessor(21695): Sent local event broadcast com.nutomic.syncthingandroid.event.FOLDERCOMPLETION including 16 extra data items.
D/EventProcessor(21695): Sent local event broadcast com.nutomic.syncthingandroid.event.FOLDERCOMPLETION including 16 extra data items.
D/EventProcessor(21695): Sent local event broadcast com.nutomic.syncthingandroid.event.FOLDERCOMPLETION including 16 extra data items.
D/EventProcessor(21695): Sent local event broadcast com.nutomic.syncthingandroid.event.FOLDERCOMPLETION including 16 extra data items.
D/EventProcessor(21695): Sent local event broadcast com.nutomic.syncthingandroid.event.FOLDERCOMPLETION including 16 extra data items.
D/EventProcessor(21695): Sent local event broadcast com.nutomic.syncthingandroid.event.FOLDERCOMPLETION including 16 extra data items.
D/EventProcessor(21695): Sent local event broadcast com.nutomic.syncthingandroid.event.FOLDERCOMPLETION including 16 extra data items.
D/EventProcessor(21695): Sent local event broadcast com.nutomic.syncthingandroid.event.FOLDERCOMPLETION including 16 extra data items.                                                                                              D/EventProcessor(21695): Sent local event broadcast com.nutomic.syncthingandroid.event.FOLDERCOMPLETION including 16 extra data items.                                                                                              D/EventProcessor(21695): Sent local event broadcast com.nutomic.syncthingandroid.event.FOLDERCOMPLETION including 16 extra data items.
I/ActivityManager( 6100):   prev  S    25477 kB: com.nutomic.syncthingandroid.debug (pid 21695) cch-started-ui-services                                                                                                             W/InputDispatcher( 6100): channel '34f5e592 com.nutomic.syncthingandroid.debug/com.nutomic.syncthingandroid.activities.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9                     E/InputDispatcher( 6100): channel '34f5e592 com.nutomic.syncthingandroid.debug/com.nutomic.syncthingandroid.activities.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
I/WindowState( 6100): WIN DEATH: Window{34f5e592 u0 com.nutomic.syncthingandroid.debug/com.nutomic.syncthingandroid.activities.MainActivity}                                                                                        W/InputDispatcher( 6100): Attempted to unregister already unregistered input channel '34f5e592 com.nutomic.syncthingandroid.debug/com.nutomic.syncthingandroid.activities.MainActivity (server)'                                    I/ActivityManager( 6100): Process com.nutomic.syncthingandroid.debug (pid 21695) has died
W/ActivityManager( 6100): Scheduling restart of crashed service com.nutomic.syncthingandroid.debug/com.nutomic.syncthingandroid.syncthing.SyncthingService in 40490ms                                                               D/StatusBar( 6387): Clicked on content of 0|com.nutomic.syncthingandroid.debug|1|null|10058
I/ActivityManager( 6100): START u0 {cmp=com.nutomic.syncthingandroid.debug/com.nutomic.syncthingandroid.activities.MainActivity} from uid 10058 on display 0                                                                        W/ActivityManager( 6100): startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { cmp=com.nutomic.syncthingandroid.debug/com.nutomic.syncthingandroid.activities.MainActivity }         I/ActivityManager( 6100): Start proc 25298:com.nutomic.syncthingandroid.debug/u0a58 for activity com.nutomic.syncthingandroid.debug/com.nutomic.syncthingandroid.activities.MainActivity                                            V/WindowManager( 6100): Adding window Window{10bfc11a u0 Starting com.nutomic.syncthingandroid.debug} at 11 of 15 (after Window{349af708 u0 org.mozilla.fennec_fdroid/org.mozilla.gecko.BrowserApp})
W/XPrivacy(25298): Hooking package=com.nutomic.syncthingandroid.debug                                             W/System.err(25298):    at com.nutomic.syncthingandroid.activities.MainActivity.$jacocoInit(MainActivity.java)    W/System.err(25298):    at com.nutomic.syncthingandroid.activities.MainActivity.<clinit>(MainActivity.java)
V/WindowManager( 6100): Adding window Window{2d49e63b u0 com.nutomic.syncthingandroid.debug/com.nutomic.syncthingandroid.activities.MainActivity} at 11 of 16 (before Window{10bfc11a u0 Starting com.nutomic.syncthingandroid.debug})                                                                                                                V/WindowManager( 6100): Adding window Window{15220b04 u0 com.nutomic.syncthingandroid.debug/com.nutomic.syncthingandroid.activities.MainActivity} at 12 of 17 (before Window{10bfc11a u0 Starting com.nutomic.syncthingandroid.debug})                                                                                                                I/ActivityManager( 6100): Displayed com.nutomic.syncthingandroid.debug/com.nutomic.syncthingandroid.activities.MainActivity: +1s885ms
I/Timeline( 6100): Timeline: Activity_windows_visible id: ActivityRecord{1fefd497 u0 com.nutomic.syncthingandroid.debug/com.nutomic.syncthingandroid.activities.MainActivity t2171} time:310724414
W/PackageManager( 6387): Failure retrieving resources for com.nutomic.syncthingandroid.debug: Resource ID #0x0    ^[

**Comment by bzzz2** [comment]
Still the same behaviour. But i dig interesting log
01-17 19:17:16.233 D/jdwp    (29531): Can't connect to ADB control socket:Connection refused
01-17 19:17:16.250 D/dalvikvm(31736): GC_CONCURRENT freed 714K, 40% free 10492K/17463K, paused 1ms+6ms
01-17 19:17:16.254 D/jdwp    (29467): Can't connect to ADB control socket:Connection refused
01-17 19:17:16.294 D/jdwp    (29496): Can't connect to ADB control socket:Connection refused
01-17 19:17:16.294 D/jdwp    (29554): Can't connect to ADB control socket:Connection refused
01-17 19:17:16.319 D/jdwp    (29126): Can't connect to ADB control socket:Connection refused
01-17 19:17:16.389 D/jdwp    (29293): Can't connect to ADB control socket:Connection refused
01-17 19:17:16.411 D/dalvikvm(31736): GC_CONCURRENT freed 752K, 39% free 10722K/17463K, paused 1ms+7ms
01-17 19:17:16.451 D/jdwp    (31431): Can't connect to ADB control socket:Connection refused
01-17 19:17:16.573 I/DEBUG   (31999): debuggerd: tmb file path:'/data/tombstones/tombstone_07'
01-17 19:17:16.574 I/DEBUG   (31999): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-17 19:17:16.574 I/DEBUG   (31999): Build fingerprint: 'Philips/Philips_W832/Philips_WG-ROVER-RU_A:4.0.4/IMM76D/1379043792.V13:user/release-keys'
01-17 19:17:16.574 I/DEBUG   (31999): pid: 31998, tid: 31998  >>> /data/data/com.nutomic.syncthingandroid.debug/lib/libsyncthing.so <<<
01-17 19:17:16.574 I/DEBUG   (31999): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00e02e68
01-17 19:17:16.574 I/DEBUG   (31999):  r0 70000001  r1 b000a508  r2 00000000  r3 00e02e68
01-17 19:17:16.574 I/DEBUG   (31999):  r4 b000afb0  r5 ffffffff  r6 00e02e68  r7 befffac8
01-17 19:17:16.574 I/DEBUG   (31999):  r8 b000a950  r9 00000000  10 00000000  fp b000811b
01-17 19:17:16.574 I/DEBUG   (31999):  ip 008b301b  sp befffa88  lr 008b257c  pc b0004648  cpsr 00000030
01-17 19:17:16.595 I/DEBUG   (31999):          #00  pc b0004648  /system/bin/linker
01-17 19:17:16.595 I/DEBUG   (31999):          #01  lr 008b257c  <unknown>
01-17 19:17:16.595 I/DEBUG   (31999): 
01-17 19:17:16.595 I/DEBUG   (31999): code around pc:
01-17 19:17:16.595 I/DEBUG   (31999): b0004628 6858e00a 208cf8d4 f8c41885 e00350d8  ..Xh... .....P..
01-17 19:17:16.595 I/DEBUG   (31999): b0004638 0895685a 50dcf8c4 e0013308 44794924  Zh.....P.3..$IyD
01-17 19:17:16.595 I/DEBUG   (31999): b0004648 2d00681d af49f47f 30acf8d4 f8d4b113  .h.-..I....0....
01-17 19:17:16.595 I/DEBUG   (31999): b0004658 b96110b0 718ef240 9100481e 4b1f4a1e  ..a.@..q.H...J.K
01-17 19:17:16.596 I/DEBUG   (31999): b0004668 491f4478 447b447a 68094479 f8d4e7b1  xD.IzD{DyD.h....
01-17 19:17:16.596 I/DEBUG   (31999): 
01-17 19:17:16.596 I/DEBUG   (31999): code around lr:
01-17 19:17:16.596 I/DEBUG   (31999): 008b255c ffffffff ffffffff ffffffff ffffffff  ................
01-17 19:17:16.596 I/DEBUG   (31999): 008b256c ffffffff ffffffff ffffffff ffffffff  ................
01-17 19:17:16.596 I/DEBUG   (31999): 008b257c ffffffff ffffffff ffffffff ffffffff  ................
01-17 19:17:16.596 I/DEBUG   (31999): 008b258c ffffffff ffffffff ffffffff ffffffff  ................
01-17 19:17:16.596 I/DEBUG   (31999): 008b259c ffffffff ffffffff ffffffff ffffffff  ................
01-17 19:17:16.596 I/DEBUG   (31999): 
01-17 19:17:16.596 I/DEBUG   (31999): memory map around addr 00e02e68:
01-17 19:17:16.596 I/DEBUG   (31999): (no map below)
01-17 19:17:16.596 I/DEBUG   (31999): (no map for address)
01-17 19:17:16.596 I/DEBUG   (31999): 2a000000-2a8b3000 /data/data/com.nutomic.syncthingandroid.debug/lib/libsyncthing.so
01-17 19:17:16.596 I/DEBUG   (31999): 
01-17 19:17:16.596 I/DEBUG   (31999): stack:
01-17 19:17:16.596 I/DEBUG   (31999):     befffa48  b000afb0  /system/bin/linker
01-17 19:17:16.596 I/DEBUG   (31999):     befffa4c  befffb10  [stack]
01-17 19:17:16.596 I/DEBUG   (31999):     befffa50  befffb6c  [stack]
01-17 19:17:16.596 I/DEBUG   (31999):     befffa54  b0003ddd  /system/bin/linker
01-17 19:17:16.596 I/DEBUG   (31999):     befffa58  00000000  
01-17 19:17:16.596 I/DEBUG   (31999):     befffa5c  00000000  
01-17 19:17:16.596 I/DEBUG   (31999):     befffa60  00000000  
01-17 19:17:16.596 I/DEBUG   (31999):     befffa64  00000000  
01-17 19:17:16.596 I/DEBUG   (31999):     befffa68  00000000  
01-17 19:17:16.596 I/DEBUG   (31999):     befffa6c  00000000  
01-17 19:17:16.596 I/DEBUG   (31999):     befffa70  00000000  
01-17 19:17:16.596 I/DEBUG   (31999):     befffa74  00000000  
01-17 19:17:16.596 I/DEBUG   (31999):     befffa78  00000000  
01-17 19:17:16.596 I/DEBUG   (31999):     befffa7c  00000000  
01-17 19:17:16.596 I/DEBUG   (31999):     befffa80  df0027ad  
01-17 19:17:16.596 I/DEBUG   (31999):     befffa84  00000000  
01-17 19:17:16.596 I/DEBUG   (31999): #00 befffa88  befffaa8  [stack]
01-17 19:17:16.597 I/DEBUG   (31999):     befffa8c  befffb6c  [stack]
01-17 19:17:16.597 I/DEBUG   (31999):     befffa90  00000001  
01-17 19:17:16.597 I/DEBUG   (31999):     befffa94  00000000  
01-17 19:17:16.597 I/DEBUG   (31999):     befffa98  00000000  
01-17 19:17:16.597 I/DEBUG   (31999):     befffa9c  00000010  
01-17 19:17:16.597 I/DEBUG   (31999):     befffaa0  befffaa8  [stack]
01-17 19:17:16.597 I/DEBUG   (31999):     befffaa4  b000afb0  /system/bin/linker
01-17 19:17:16.597 I/DEBUG   (31999):     befffaa8  b000a4f4  /system/bin/linker
01-17 19:17:16.597 I/DEBUG   (31999):     befffaac  00000002  
01-17 19:17:16.597 I/DEBUG   (31999):     befffab0  befffac8  [stack]
01-17 19:17:16.597 I/DEBUG   (31999):     befffab4  b000a950  /system/bin/linker
01-17 19:17:16.597 I/DEBUG   (31999):     befffab8  00000000  
01-17 19:17:16.597 I/DEBUG   (31999):     befffabc  00000000  
01-17 19:17:16.597 I/DEBUG   (31999):     befffac0  b000811b  /system/bin/linker
01-17 19:17:16.597 I/DEBUG   (31999):     befffac4  b0004c75  /system/bin/linker
01-17 19:17:16.597 I/DEBUG   (31999):     befffac8  00000000  
01-17 19:17:16.597 I/DEBUG   (31999):     befffacc  00000000  
01-17 19:17:16.604 D/dalvikvm(31736): GC_CONCURRENT freed 840K, 38% free 11000K/17463K, paused 1ms+8ms
01-17 19:17:16.617 D/AEE/AED (31999): Skip for Exp level'0'
01-17 19:17:16.618 D/AEE/AED (92): $===AEE===AEE===AEE===$
01-17 19:17:16.618 D/AEE/AED (92): p 0 poll events 1 revents 0
01-17 19:17:16.618 D/AEE/AED (92): not know revents:0
01-17 19:17:16.618 D/AEE/AED (92): p 1 poll events 1 revents 0
01-17 19:17:16.618 D/AEE/AED (92): not know revents:0
01-17 19:17:16.618 D/AEE/AED (92): p 2 poll events 1 revents 0
01-17 19:17:16.618 D/AEE/AED (92): not know revents:0
01-17 19:17:16.618 D/AEE/AED (92): p 3 poll events 1 revents 0
01-17 19:17:16.618 D/AEE/AED (92): not know revents:0
01-17 19:17:16.618 D/AEE/AED (92): p 4 poll events 1 revents 0
01-17 19:17:16.618 D/AEE/AED (92): not know revents:0
01-17 19:17:16.618 I/BootReceiver(229): Copying /data/tombstones/tombstone_07 to DropBox (SYSTEM_TOMBSTONE)
01-17 19:17:16.620 D/dalvikvm(31582): threadid=15: exiting
01-17 19:17:16.620 D/dalvikvm(31582): threadid=15: bye!
01-17 19:17:16.620 D/dalvikvm(31582): threadid=0: freeing
01-17 19:17:16.621 D/dalvikvm(31582): threadid=16: exiting
01-17 19:17:16.621 D/dalvikvm(31582): threadid=16: bye!
01-17 19:17:16.621 D/dalvikvm(31582): threadid=0: freeing
01-17 19:17:16.622 I/System  (31582): Failed to destroy process 31998
01-17 19:17:16.624 I/System  (31582): libcore.io.ErrnoException: kill failed: ESRCH (No such process)
01-17 19:17:16.624 I/System  (31582): 	at libcore.io.Posix.kill(Native Method)
01-17 19:17:16.624 I/System  (31582): 	at libcore.io.ForwardingOs.kill(ForwardingOs.java:77)
01-17 19:17:16.624 I/System  (31582): 	at java.lang.ProcessManager$ProcessImpl.destroy(ProcessManager.java:257)
01-17 19:17:16.624 I/System  (31582): 	at com.nutomic.syncthingandroid.syncthing.SyncthingRunnable.run(SyncthingRunnable.java:136)
01-17 19:17:16.624 I/System  (31582): 	at com.nutomic.syncthingandroid.util.ConfigXml.generateKeysConfig(ConfigXml.java:104)
01-17 19:17:16.624 I/System  (31582): 	at com.nutomic.syncthingandroid.util.ConfigXml.<init>(ConfigXml.java:89)
01-17 19:17:16.624 I/System  (31582): 	at com.nutomic.syncthingandroid.syncthing.SyncthingService.updateState(SyncthingService.java:236)
01-17 19:17:16.624 I/System  (31582): 	at com.nutomic.syncthingandroid.syncthing.SyncthingService.onStartCommand(SyncthingService.java:193)
01-17 19:17:16.624 I/System  (31582): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2501)
01-17 19:17:16.624 I/System  (31582): 	at android.app.ActivityThread.access$1900(ActivityThread.java:134)
01-17 19:17:16.624 I/System  (31582): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1310)
01-17 19:17:16.624 I/System  (31582): 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-17 19:17:16.624 I/System  (31582): 	at android.os.Looper.loop(Looper.java:154)
01-17 19:17:16.624 I/System  (31582): 	at android.app.ActivityThread.main(ActivityThread.java:4624)
01-17 19:17:16.624 I/System  (31582): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-17 19:17:16.624 I/System  (31582): 	at java.lang.reflect.Method.invoke(Method.java:511)
01-17 19:17:16.624 I/System  (31582): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:809)
01-17 19:17:16.624 I/System  (31582): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:576)
01-17 19:17:16.624 I/System  (31582): 	at dalvik.system.NativeStart.main(Native Method)
01-17 19:17:16.624 E/SyncthingNativeCode(31582): Syncthing binary crashed with error code 11
01-17 19:17:16.625 W/ConfigXml(31582): Failed to open config, moving to config.xml.invalid and creating blank config
01-17 19:17:16.633 V/ActivityManager(229): Broadcast: Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } ordered=false
01-17 19:17:16.658 F/libc    (32004): Fatal signal 11 (SIGSEGV) at 0x00e02e68 (code=1)
01-17 19:17:16.658 D/AEE/AED (92): $===AEE===AEE===AEE===$
01-17 19:17:16.658 D/AEE/AED (92): p 0 poll events 1 revents 0
01-17 19:17:16.658 D/AEE/AED (92): not know revents:0
01-17 19:17:16.658 D/AEE/AED (92): p 1 poll events 1 revents 0
01-17 19:17:16.658 D/AEE/AED (92): not know revents:0
01-17 19:17:16.658 D/AEE/AED (92): p 2 poll events 1 revents 1
01-17 19:17:16.658 D/AEE/AED (92): aed_main_fork_worker: generator 0x14db038, worker 0xbe919b78, recv_fd 19
01-17 19:17:16.658 D/AEE/AED (92): p 3 poll events 1 revents 0
01-17 19:17:16.658 D/AEE/AED (92): not know revents:0
01-17 19:17:16.658 D/AEE/AED (92): p 4 poll events 1 revents 0
01-17 19:17:16.658 D/AEE/AED (92): not know revents:0
01-17 19:17:16.660 I/DEBUG   (32005): BOOM: pid=32004 uid=10063 gid=10063 tid=32004
01-17 19:17:16.661 D/dalvikvm(31582): threadid=15: interp stack at 0x48f7f000
01-17 19:17:16.661 D/dalvikvm(31582): threadid=15: calling run()
01-17 19:17:16.662 D/dalvikvm(31582): threadid=16: interp stack at 0x493e7000
01-17 19:17:16.662 D/dalvikvm(31582): threadid=16: calling run()
01-17 19:17:16.662 D/dalvikvm(31582): threadid=20: interp stack at 0x493ff000
01-17 19:17:16.662 D/dalvikvm(31582): threadid=20: calling run()
01-17 19:17:16.728 D/jdwp    (385): Can't connect to ADB control socket:Connection refused
01-17 19:17:16.742 D/jdwp    (320): Can't connect to ADB control socket:Connection refused
01-17 19:17:16.742 D/jdwp    (426): Can't connect to ADB control socket:Connection refused
01-17 19:17:16.742 D/jdwp    (433): Can't connect to ADB control socket:Connection refused
01-17 19:17:16.751 D/jdwp    (411): Can't connect to ADB control socket:Connection refused
01-17 19:17:16.769 D/jdwp    (30167): Can't connect to ADB control socket:Connection refused
01-17 19:17:16.776 D/dalvikvm(31582): threadid=21: interp stack at 0x49407000
01-17 19:17:16.776 D/dalvikvm(31582): threadid=21: calling run()
01-17 19:17:16.816 W/ProcessStats(229): Skipping unknown process pid 32011
01-17 19:17:16.840 D/dalvikvm(31582): threadid=21: exiting
01-17 19:17:16.840 D/dalvikvm(31582): threadid=21: bye!
01-17 19:17:16.840 D/dalvikvm(31582): threadid=0: freeing
01-17 19:17:16.840 I/SyncthingRunnableIoNice(31582): ionice performed on libsyncthing.so
01-17 19:17:16.840 I/System  (31582): Failed to destroy process 32009
01-17 19:17:16.841 I/System  (31582): libcore.io.ErrnoException: kill failed: ESRCH (No such process)
01-17 19:17:16.841 I/System  (31582): 	at libcore.io.Posix.kill(Native Method)
01-17 19:17:16.841 I/System  (31582): 	at libcore.io.ForwardingOs.kill(ForwardingOs.java:77)
01-17 19:17:16.841 I/System  (31582): 	at java.lang.ProcessManager$ProcessImpl.destroy(ProcessManager.java:257)
01-17 19:17:16.841 I/System  (31582): 	at com.nutomic.syncthingandroid.syncthing.SyncthingRunnable$1.run(SyncthingRunnable.java:183)
01-17 19:17:16.841 D/dalvikvm(31582): threadid=17: exiting
01-17 19:17:16.842 D/dalvikvm(31582): threadid=17: bye!
01-17 19:17:16.842 D/dalvikvm(31582): threadid=0: freeing

**Comment by pascalfree** [comment]
The Build with Go 1.6 beta still fails to start for me.
[Log-2016-01-18-07.26.34.csv.txt](https://github.com/syncthing/syncthing-android/files/93908/Log-2016-01-18-07.26.34.csv.txt)

In the meantime I got a new phone and will give the phone with the issue back to the original owner. Thus I'm no longer affected by the issue and can no longer check if newer builds are working.
I'll leave the issue open for others having the same issue.

Thank you for the support.

**Comment by irregularisnotrandom** [comment]
0.7.6 still crashes on Android 4.1. I have not tried it on other devices yet.

Maybe memory usage causing issues with the kernel?

**Comment by Unrud** [comment]
I also get error code 11 on Android 4.0.3.
I compiled 0ce49622650dc1cbbc6999ac970ff193f274d041 without CGO and it works fine.

**Comment by Zillode** [comment]
So this looks hard to fix from our end. We can either go back to the non-cgo version but loose DNS support, or bundle both versions and use it as a fallback (but then the size will be quite large).

**Comment by Nutomic** [comment]
I guess the best solution would be to get these bugs fixed in golang. Though that will probably take some time. @Zillode Can you at least open an issue on their tracker?

**Comment by gerroon** [comment]
I have started using the regular syncthing arm builds and those regular arm builds seems to not manifest any hidden crashes. I the arm binary since 0.7.5 has been sketchy at best for me.

Maybe you can release the noncgo versions here so we can install them manually.

**Comment by Nutomic** [comment]
Can people with this issue test the [apk in #547](https://github.com/syncthing/syncthing-android/pull/547#issuecomment-175269141) and comment on the pr?

**Comment by MStrecke** [comment]
I also have the problem with an old "Lifetab P9514" (Medion).
Android 4.0.3

I've tried the above mentioned APK, no luck
````
02-08 15:34:57.620 2444-2444/? I/dalvikvm: Could not find method android.net.ConnectivityManager.isActiveNetworkMetered, referenced from method com.nutomic.syncthingandroid.syncthing.DeviceStateHolder.<init>
02-08 15:34:57.620 2444-2444/? W/dalvikvm: VFY: unable to resolve virtual method 588: Landroid/net/ConnectivityManager;.isActiveNetworkMetered ()Z
02-08 15:34:57.620 2444-2444/? D/dalvikvm: VFY: replacing opcode 0x6e at 0x0023
02-08 15:34:57.650 2444-2446/? D/dalvikvm: GC_CONCURRENT freed 240K, 5% free 7001K/7303K, paused 2ms+2ms
02-08 15:34:57.810 2444-2457/? I/ConfigXml: Checking for needed config updates
02-08 15:34:57.950 2444-2444/? D/libEGL: loaded /system/lib/egl/libEGL_tegra.so
02-08 15:34:58.060 2444-2444/? D/libEGL: loaded /system/lib/egl/libGLESv1_CM_tegra.so
02-08 15:34:58.180 2444-2444/? D/libEGL: loaded /system/lib/egl/libGLESv2_tegra.so
02-08 15:34:58.220 2444-2444/? D/OpenGLRenderer: Enabling debug mode 0
02-08 15:34:58.220 2444-2444/? I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
02-08 15:34:58.440 2444-2444/? I/SyncthingService: Web GUI will be available at https://127.0.0.1:8384
02-08 15:34:58.440 2444-2444/? D/EventProcessor: Shutdown event processor.
02-08 15:34:58.440 2444-2444/? I/SyncthingService: Starting syncthing according to current state and preferences
02-08 15:34:58.470 2444-2444/? I/ConfigXml: Checking for needed config updates
02-08 15:34:58.510 174-373/? W/InputManagerService: Starting input on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@417967a0 (uid=10023 pid=446)
02-08 15:34:58.600 2444-2446/? D/dalvikvm: GC_CONCURRENT freed 228K, 5% free 7191K/7495K, paused 2ms+5ms
02-08 15:34:58.620 2465-2465/? A/libc: Fatal signal 11 (SIGSEGV) at 0x00e17e64 (code=1)
02-08 15:34:58.830 174-210/? I/ActivityManager: Displayed com.nutomic.syncthingandroid/.activities.MainActivity: +1s924ms
02-08 15:34:59.060 100-100/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-08 15:34:59.060 100-100/? I/DEBUG: Build fingerprint: 'Quanta/LIFETAB_P9514_de/LIFETAB_P9514:4.0.3/IML74K/eng.20120719.095929:user/release-keys'
02-08 15:34:59.060 100-100/? I/DEBUG: pid: 2465, tid: 2465  >>> /data/data/com.nutomic.syncthingandroid/lib/libsyncthing.so <<<
02-08 15:34:59.060 100-100/? I/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00e17e64
02-08 15:34:59.060 100-100/? I/DEBUG:  r0 70000001  r1 b00094fc  r2 00000000  r3 00e17e64
02-08 15:34:59.060 100-100/? I/DEBUG:  r4 b0009f60  r5 ffffffff  r6 00e17e64  r7 be913af8
02-08 15:34:59.060 100-100/? I/DEBUG:  r8 b0009910  r9 00000000  10 00000000  fp b0006f1f
02-08 15:34:59.060 100-100/? I/DEBUG:  ip 008c001b  sp be913ab8  lr 008bf67c  pc b00043c8  cpsr 00000030
02-08 15:34:59.060 100-100/? I/DEBUG:  d0  0000000000000000  d1  0000000000000000
02-08 15:34:59.060 100-100/? I/DEBUG:  d2  0000000000000000  d3  0000000000000000
02-08 15:34:59.060 100-100/? I/DEBUG:  d4  0000000000000000  d5  0000000000000000
02-08 15:34:59.060 100-100/? I/DEBUG:  d6  0000000000000000  d7  0000000000000000
02-08 15:34:59.060 100-100/? I/DEBUG:  d8  0000000000000000  d9  0000000000000000
02-08 15:34:59.060 100-100/? I/DEBUG:  d10 0000000000000000  d11 0000000000000000
02-08 15:34:59.060 100-100/? I/DEBUG:  d12 0000000000000000  d13 0000000000000000
02-08 15:34:59.060 100-100/? I/DEBUG:  d14 0000000000000000  d15 0000000000000000
02-08 15:34:59.060 100-100/? I/DEBUG:  scr 00000000
02-08 15:34:59.100 100-100/? I/DEBUG:          #00  pc b00043c8  /system/bin/linker
02-08 15:34:59.100 100-100/? I/DEBUG:          #01  lr 008bf67c  <unknown>
02-08 15:34:59.100 100-100/? I/DEBUG: b00043a8 6858e00a 208cf8d4 f8c41885 e00350d8  ..Xh... .....P..
02-08 15:34:59.100 100-100/? I/DEBUG: b00043b8 0895685a 50dcf8c4 e0013308 44794924  Zh.....P.3..$IyD
02-08 15:34:59.100 100-100/? I/DEBUG: b00043c8 2d00681d af49f47f 30acf8d4 f8d4b113  .h.-..I....0....
02-08 15:34:59.100 100-100/? I/DEBUG: b00043d8 b96110b0 7174f240 9100481e 44784a1e  ..a.@.tq.H...JxD
02-08 15:34:59.100 100-100/? I/DEBUG: b00043e8 491f4b1e 447b447a 68094479 f8d4e7b1  .K.IzD{DyD.h....
02-08 15:34:59.100 100-100/? I/DEBUG: 008bf65c ffffffff ffffffff ffffffff ffffffff  ................
02-08 15:34:59.100 100-100/? I/DEBUG: 008bf66c ffffffff ffffffff ffffffff ffffffff  ................
02-08 15:34:59.100 100-100/? I/DEBUG: 008bf67c ffffffff ffffffff ffffffff ffffffff  ................
02-08 15:34:59.100 100-100/? I/DEBUG: 008bf68c ffffffff ffffffff ffffffff ffffffff  ................
02-08 15:34:59.100 100-100/? I/DEBUG: 008bf69c ffffffff ffffffff ffffffff ffffffff  ................
02-08 15:34:59.100 100-100/? I/DEBUG: (no map below)
02-08 15:34:59.110 100-100/? I/DEBUG: (no map for address)
02-08 15:34:59.110 100-100/? I/DEBUG: 400c2000-40982000 /data/data/com.nutomic.syncthingandroid/lib/libsyncthing.so
02-08 15:34:59.110 100-100/? I/DEBUG:     be913a78  00000000  
02-08 15:34:59.110 100-100/? I/DEBUG:     be913a7c  00000000  
02-08 15:34:59.110 100-100/? I/DEBUG:     be913a80  00000000  
02-08 15:34:59.110 100-100/? I/DEBUG:     be913a84  00000000  
02-08 15:34:59.110 100-100/? I/DEBUG:     be913a88  00000000  
02-08 15:34:59.110 100-100/? I/DEBUG:     be913a8c  00000000  
02-08 15:34:59.110 100-100/? I/DEBUG:     be913a90  00000000  
02-08 15:34:59.110 100-100/? I/DEBUG:     be913a94  00000000  
02-08 15:34:59.110 100-100/? I/DEBUG:     be913a98  00000000  
02-08 15:34:59.110 100-100/? I/DEBUG:     be913a9c  00000000  
02-08 15:34:59.110 100-100/? I/DEBUG:     be913aa0  00000000  
02-08 15:34:59.110 100-100/? I/DEBUG:     be913aa4  00000000  
02-08 15:34:59.110 100-100/? I/DEBUG:     be913aa8  00000000  
02-08 15:34:59.110 100-100/? I/DEBUG:     be913aac  00000000  
02-08 15:34:59.110 100-100/? I/DEBUG:     be913ab0  df0027ad  
02-08 15:34:59.110 100-100/? I/DEBUG:     be913ab4  00000000  
02-08 15:34:59.110 100-100/? I/DEBUG: #00 be913ab8  00000000  
02-08 15:34:59.110 100-100/? I/DEBUG:     be913abc  00000000  
02-08 15:34:59.110 100-100/? I/DEBUG:     be913ac0  b0009f60  /system/bin/linker
02-08 15:34:59.110 100-100/? I/DEBUG:     be913ac4  b0009f60  /system/bin/linker
02-08 15:34:59.110 100-100/? I/DEBUG:     be913ac8  be913c52  [stack]
02-08 15:34:59.110 100-100/? I/DEBUG:     be913acc  00000118  
02-08 15:34:59.110 100-100/? I/DEBUG:     be913ad0  b0009f60  /system/bin/linker
02-08 15:34:59.110 100-100/? I/DEBUG:     be913ad4  b0009f60  /system/bin/linker
02-08 15:34:59.110 100-100/? I/DEBUG:     be913ad8  b00094f0  /system/bin/linker
02-08 15:34:59.110 100-100/? I/DEBUG:     be913adc  00000002  
02-08 15:34:59.110 100-100/? I/DEBUG:     be913ae0  be913af8  [stack]
02-08 15:34:59.110 100-100/? I/DEBUG:     be913ae4  b0009910  /system/bin/linker
02-08 15:34:59.110 100-100/? I/DEBUG:     be913ae8  00000000  
02-08 15:34:59.110 100-100/? I/DEBUG:     be913aec  00000000  
02-08 15:34:59.110 100-100/? I/DEBUG:     be913af0  b0006f1f  /system/bin/linker
02-08 15:34:59.110 100-100/? I/DEBUG:     be913af4  b00049f5  /system/bin/linker
02-08 15:34:59.110 100-100/? I/DEBUG:     be913af8  00000000  
02-08 15:34:59.110 100-100/? I/DEBUG:     be913afc  00000000  
02-08 15:34:59.130 2444-2461/? I/System: Failed to destroy process 2465
02-08 15:34:59.130 2444-2461/? I/System: libcore.io.ErrnoException: kill failed: ESRCH (No such process)
                                             at libcore.io.Posix.kill(Native Method)
                                             at libcore.io.ForwardingOs.kill(ForwardingOs.java:77)
                                             at java.lang.ProcessManager$ProcessImpl.destroy(ProcessManager.java:257)
                                             at com.nutomic.syncthingandroid.syncthing.SyncthingRunnable.run(SyncthingRunnable.java:144)
                                             at java.lang.Thread.run(Thread.java:856)
02-08 15:34:59.130 2444-2461/? E/SyncthingNativeCode: Syncthing binary crashed with error code 11
02-08 15:34:59.130 174-197/? I/BootReceiver: Copying /data/tombstones/tombstone_00 to DropBox (SYSTEM_TOMBSTONE)
02-08 15:34:59.230 361-363/? D/dalvikvm: GC_CONCURRENT freed 519K, 7% free 8649K/9287K, paused 5ms+5ms
02-08 15:34:59.940 2444-2472/? W/SyncthingNativeCode: sh: <stdin>[1]: grep: not found
02-08 15:34:59.960 2444-2472/? W/SyncthingNativeCode: usage: ionice <pid> [none|rt|be|idle] [prio]
02-08 15:34:59.960 2444-2468/? I/SyncthingRunnableIoNice: ionice performed on libsyncthing.so
02-08 15:34:59.960 2444-2468/? I/System: Failed to destroy process 2471
02-08 15:34:59.960 2444-2468/? I/System: libcore.io.ErrnoException: kill failed: ESRCH (No such process)
                                             at libcore.io.Posix.kill(Native Method)
                                             at libcore.io.ForwardingOs.kill(ForwardingOs.java:77)
                                             at java.lang.ProcessManager$ProcessImpl.destroy(ProcessManager.java:257)
                                             at com.nutomic.syncthingandroid.syncthing.SyncthingRunnable$1.run(SyncthingRunnable.java:199)
02-08 15:34:59.960 2444-2468/? E/SyncthingRunnableIoNice: Failed to set ionice 1
````

**Comment by Nutomic** [comment]
I've updated the Go compiler to 1.6-rc2 for the next release, maybe that fixes this problem.

**Comment by AudriusButkevicius** [comment]
It doesn't. I am pretty sure that it's either CGO, or non-static builds.

**Comment by Nutomic** [comment]
@AudriusButkevicius Any clue about fixing this? I know absolutely nothing about Go, so help would be great ;)

**Comment by gerroon** [comment]
Hi

Any word on this? 

This app still does "loading" everytime I click on the notification tray. 

thanks

**Comment by Nutomic** [comment]
This issue should also be fixed with the latest version. Please comment/reopen if that is not the case.

**Comment by gerroon** [comment]
I still get crashes although not as much I guess. These crashes were very frequent with a x86 device but I do not have the device anymore.

**Comment by Nutomic** [comment]
Those are probably different crashes, please open an issue when you have logs.
