### ISSUE TITLE
Syncthing Android UI crashes on launch on Source method getMenu in Source class android.support.v7.widget.ActionMenuView

### ISSUE THREAD

**Issue by actinmyosin** [syncthing/syncthing-android#591]
Syncthing Android UI immediately crashes on launch on Source method getMenu in Source class android.support.v7.widget.ActionMenuView

Per web searches for this topic, this can be addressed by using a try-catch statement around the menu call as documented at:
https://www.reddit.com/r/androiddev/comments/2lluck/appcompatv7_v2100_causing_crash_on_samsung/clwd14p

try {
((ActionBarActivity) activity).setSupportActionBar(toolbar);
} catch (Throwable t) {
// do nothing
}

Other search results say that Proguard can also take care of the problem.
Version Information

Syncthing Version: v0.7.11
OS Version: Android 4.2.2 on Samsung SCH-I435 aka serranoltevzw

**Comment by veniosg** [comment]
I'm not sure about the cause of the issue but regardless, I would advice
against catching and swallowing Throwables as it's too broad a net and can
hide real issues and cause unexpected behaviour for the end user.

**Comment by actinmyosin** [comment]
Generally that makes sense, but here we have an issue on Android 4.2.2 on Samsung devices that can be addressed pretty easily with a try-catch. At a minimum the try-catch can make it into a non-fatal error.

If Google, the device makers, and carriers had their acts together, this wouldn't be necessary. Per my searches, other Samsung devices are also affected.

**Comment by veniosg** [comment]
Don't get me wrong, try/catching is a valid fix in many cases, and maybe
this one too. What I'm advising against is catching the base class
"Throwable" instead of the specific one being thrown by this issue, and
then even swallowing it.

**Comment by actinmyosin** [comment]
More on the topic with Proguard details/examples:
http://stackoverflow.com/questions/24809580/noclassdeffounderror-android-support-v7-internal-view-menu-menubuilder/27254191#27254191
http://developer.samsung.com/forum/board/thread/view.do?boardName=General&messageId=248142

**Comment by Nutomic** [comment]
It says [here](https://code.google.com/p/android/issues/detail?id=78377#c364) that this is fixed in the support library 24.0.0-alpha1. But I'm not sure when that will be released.

Alternatively, we can catch the exception, which is `java.lang.NoClassDefFoundError: android.support.v7.internal.view.menu.MenuBuilder`.

**Comment by actinmyosin** [comment]
It seems the problem persists on 0.7.12. Can this be reopened?
Exception class name: java.lang.NoClassDefFoundError
Source file: ActionMenuView.java
Source class: android.support.v7.widget.ActionMenuView
Source method: getMenu
Line number: 642

**Comment by Nutomic** [comment]
@actinmyosin Can you post a full logcat of the crash?

**Comment by actinmyosin** [comment]
Maybe this will help? I saved it using the CatLog app while attempting to run Syncthing 0.7.12. ID and apiKey has been changed. Attached: [logcat-syncthing-2016-03-25.txt](https://github.com/syncthing/syncthing-android/files/190358/logcat-syncthing-2016-03-25.txt)

Also, are you able to extract info from the Android crash reporter/submitter?

**Comment by Nutomic** [comment]
`[PO5RI] 04:58:06 FATAL: Cannot open database: resource temporarily unavailable - Is another copy of Syncthing already running?`

That's the only error I see, maybe you missed an earlier one?

I also see some crash reports in Google Play for NoClassDefFoundError (S4 Mini and Wiko), but none of our code is even in the stack trace. That suggests it's a bug in the support library, and nothing we can fix.

```
java.lang.NoClassDefFoundError: android.support.v7.view.menu.MenuBuilder
	at android.support.v7.widget.ActionMenuView.getMenu(ActionMenuView.java:642)
	at android.support.v7.widget.Toolbar.ensureMenu(Toolbar.java:868)
	at android.support.v7.widget.Toolbar.getMenu(Toolbar.java:839)
	at android.support.v7.widget.ToolbarWidgetWrapper.getMenu(ToolbarWidgetWrapper.java:694)
	at android.support.v7.app.ToolbarActionBar.getMenu(ToolbarActionBar.java:578)
	at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:436)
	at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:60)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:776)
	at android.view.Choreographer.doCallbacks(Choreographer.java:579)
	at android.view.Choreographer.doFrame(Choreographer.java:547)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:762)
	at android.os.Handler.handleCallback(Handler.java:800)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5391)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by actinmyosin** [comment]
I don't see another crash entry. The crash is known on both of the devices you mentioned for other apps too. I read through much of the URL you shared about the support library.

Post 365 at https://code.google.com/p/android/issues/detail?id=78377#c365
says to try v24 as it worked for him:
compile 'com.android.support:appcompat-v7:24.0.0-alpha1'

Other posts that look relevant:
Post 258 has a thorough workaround example/wrapper/design that specifically says to not use `setSupportActionBar(toolbar)`'.
https://code.google.com/p/android/issues/detail?id=78377#c258

Posts 319, 308, and 313, look to be closely relevant to the details of the crash report: 
https://code.google.com/p/android/issues/detail?id=78377#c319
https://code.google.com/p/android/issues/detail?id=78377#c308
https://code.google.com/p/android/issues/detail?id=78377#c313

Is it possible to try the v24 alpha newer support library? I think v24 is the best option, if it works. Or try falling back to the v22 support library? If you can make a custom apk build, I can sideload it to test things out without going through the Play store.

**Comment by Nutomic** [comment]
Switching to appcompat 24 is obviously the right solution for this, but I'm not gonna switch to an alpha version. That will just give us more problems. And we can't use appcompat 22 because we use some newer features. 

So I guess you'll have to wait for an update of the support lib.
