### ISSUE TITLE
0.8.6 continually crashes / freezes

### ISSUE THREAD

**Issue by phil99** [syncthing/syncthing-android#767]
Since install of 0.8.6, all 3 of my Android devices are crashing or freezing repeatedly.
Many times have crashed entire device leading to a reboot.
Have been using ST a year and never happened before.
Android v4.2.2, v4.2.3

**Comment by licaon-kter** [comment]
Can you save a log? Get a logcat? Something?

**Comment by phil99** [comment]
I have sent in crash reports when it has allowed me, often kills everything, so no opportunity.
I'll see what I can find next time it crashes.

**Comment by licaon-kter** [comment]
If root save one via Termux or via aLogcatRoot.
Without root, get developer on and use a PC with ADB.

**Comment by phil99** [comment]
These are the Logs after an "Unfortunately Syncthing has stopped" message.
Did not hang, or crash the device.

I will send in more logs if/when they are available post-crash.

[Android Log.txt](https://github.com/syncthing/syncthing-android/files/544347/Android.Log.txt)

[Syncthing Log.txt](https://github.com/syncthing/syncthing-android/files/544348/Syncthing.Log.txt)

**Comment by phil99** [comment]
This issue closed in error. Not resolved.

**Comment by Nutomic** [comment]
There are no errors in those logs. Maybe you have to start logging before the error is shown.

**Comment by phil99** [comment]
The log was started when ST started, and ended when it crashed. It must have my recorded the event.

**Comment by phil99** [comment]
For "my" read "not" - predictive keyboards!

**Comment by Nutomic** [comment]
How did you record the log? If you used grep, it might have missed some lines.

**Comment by phil99** [comment]
This is Syncthing Log output with debug options set to Scanner,model

I have no idea what grep is

**Comment by phil99** [comment]
Further log output on another crash

--------- beginning of /dev/log/main
--------- beginning of /dev/log/system
I/SyncthingNativeCode( 3345): [Z4T2T] 15:05:46 INFO: syncthing v0.14.8 "Dysprosium Dragonfly" (go1.6.2 linux-arm) unknown-user@P50 2016-10-03 23:12:55 UTC
I/SyncthingNativeCode( 3345): [Z4T2T] 15:05:46 INFO: My ID: Z4T2TFU-VRWXJ7E-LILZZEA-U46R32C-REUPAMP-R7OL2W2-5426Y7J-U3DDVA3
I/SyncthingNativeCode( 3345): [Z4T2T] 15:05:47 INFO: Single thread hash performance is 13 MB/s using minio/sha256-simd (13 MB/s using crypto/sha256).
I/SyncthingNativeCode( 3345): [Z4T2T] 15:05:47 FATAL: Cannot open database: resource temporarily unavailable - Is another copy of Syncthing already running?

**Comment by Nutomic** [comment]
It just says that Syncthing is already running. If you go to System Settings -> Apps -> Syncthing, and press Force Stop, it should work again.

**Comment by phil99** [comment]
@Nutomic 

That threw me.

Have been using 0.8.4 for a while with no issues, now I have installed 0.8.7 and straight away it's crashing again. Again the Syncthing log shows the same error, I do not understand why there should be another instance running, unless it trying to open another itself. All I was doing was trying to add a new folder.

Here is the Syncthing log:
--------- beginning of /dev/log/main
I/SyncthingNativeCode( 4741): [EQRNZ] 17:32:52 INFO: syncthing v0.14.9 "Dysprosium Dragonfly" (go1.6.2 linux-arm) unknown-user@P50 2016-10-17 07:21:58 UTC
I/SyncthingNativeCode( 4741): [EQRNZ] 17:32:52 INFO: My ID: EQRNZXG-ZXX4A4R-6O6OOVB-DCSN4XI-LZAI7A6-TQTZJN7-R6QUF2Z-RGHX2AD
I/SyncthingNativeCode( 4741): [EQRNZ] 17:32:53 INFO: Single thread hash performance is 8.7 MB/s using minio/sha256-simd (8.3 MB/s using crypto/sha256).
I/SyncthingNativeCode( 4741): [EQRNZ] 17:32:53 FATAL: Cannot open database: resource temporarily unavailable - Is another copy of Syncthing already running?

And a section of the Android log showing FATAL EXCEPTION:
V/GetTask ( 3728): Calling Rest API at https://127.0.0.1:8384/rest/events?since=0&limit=1
V/GetTask ( 3728): API call result: [{"id":3,"globalID":3,"time":"2016-10-28T17:19:00.258338344Z","type":"Ping","data":null}]
D/EventProcessor( 3728): Reading events starting with id 3
V/GetTask ( 3728): Calling Rest API at https://127.0.0.1:8384/rest/events?since=3&limit=0
I/dalvikvm( 3728): Could not find method com.nutomic.syncthingandroid.activities.FolderPickerActivity.getExternalFilesDirs, referenced from method com.nutomic.syncthingandroid.activities.FolderPickerActivity.populateRoots
W/dalvikvm( 3728): VFY: unable to resolve virtual method 36509: Lcom/nutomic/syncthingandroid/activities/FolderPickerActivity;.getExternalFilesDirs (Ljava/lang/String;)[Ljava/io/File;
D/dalvikvm( 3728): VFY: replacing opcode 0x6e at 0x000c
D/dalvikvm( 3728): DexOpt: couldn't find static field Landroid/os/Environment;.DIRECTORY_DOCUMENTS
W/dalvikvm( 3728): VFY: unable to resolve static field 110 (DIRECTORY_DOCUMENTS) in Landroid/os/Environment;
D/dalvikvm( 3728): VFY: replacing opcode 0x62 at 0x0052
D/AndroidRuntime( 3728): Shutting down VM
W/dalvikvm( 3728): threadid=1: thread exiting with uncaught exception (group=0x41c1d930)
--------- beginning of /dev/log/system
E/AndroidRuntime( 3728): FATAL EXCEPTION: main
E/AndroidRuntime( 3728): java.lang.NoSuchFieldError: android.os.Environment.DIRECTORY_DOCUMENTS
E/AndroidRuntime( 3728): 	at com.nutomic.syncthingandroid.activities.FolderPickerActivity.populateRoots(FolderPickerActivity.java:107)
E/AndroidRuntime( 3728): 	at com.nutomic.syncthingandroid.activities.FolderPickerActivity.onCreate(FolderPickerActivity.java:76)
E/AndroidRuntime( 3728): 	at android.app.Activity.performCreate(Activity.java:5104)
E/AndroidRuntime( 3728): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
E/AndroidRuntime( 3728): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
E/AndroidRuntime( 3728): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
E/AndroidRuntime( 3728): 	at android.app.ActivityThread.access$600(ActivityThread.java:141)
E/AndroidRuntime( 3728): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
E/AndroidRuntime( 3728): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 3728): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 3728): 	at android.app.ActivityThread.main(ActivityThread.java:5041)
E/AndroidRuntime( 3728): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 3728): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 3728): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
E/AndroidRuntime( 3728): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
E/AndroidRuntime( 3728): 	at dalvik.system.NativeStart.main(Native Method)
I/Process ( 3728): Sending signal. PID: 3728 SIG: 9
I/dalvikvm( 4107): Could not find method android.os.PowerManager.isPowerSaveMode, referenced from method com.nutomic.syncthingandroid.syncthing.DeviceStateHolder.shouldRun
W/dalvikvm( 4107): VFY: unable to resolve virtual method 1314: Landroid/os/PowerManager;.isPowerSaveMode ()Z
D/dalvikvm( 4107): VFY: replacing opcode 0x6e at 0x0012
D/dalvikvm( 4107): GC_CONCURRENT freed 247K, 14% free 2571K/2980K, paused 30ms+14ms, total 133ms
I/ConfigXml( 4107): Checking for needed config updates
I/SyncthingService( 4107): Web GUI will be available at https://127.0.0.1:8384
D/EventProcessor( 4107): Shutdown event processor.

**Comment by phil99** [comment]
Further info after repeatedly testing v0.8.7 (new install from scratch):

1) 0.8.7 crashes when selecting "directory" input field in "ADD FOLDER".

2) The logs submitted in my last post are output from this event.
This behaviour is repeatable.

3) As I cannot add a folder, I cannot test 0.8.7 for the crash scenarios that were occurring in 0.8.6.

4) Why the "Syncthing" Log reports:
I/SyncthingNativeCode(__ 3345): [Z4T2T] 15:05:47 FATAL: Cannot open database: resource temporarily unavailable - Is another copy of Syncthing already running?

I cannot explain, there is no other instance running that I can identify.

5) The "Android" Log reports:
I/dalvikvm( 3728): Could not find method com.nutomic.syncthingandroid.activities.FolderPickerActivity.getExternalFilesDirs, referenced from method com.nutomic.syncthingandroid.activities.FolderPickerActivity.populateRoots
W/dalvikvm( 3728): VFY: unable to resolve virtual method 36509: Lcom/nutomic/syncthingandroid/activities/FolderPickerActivity;.getExternalFilesDirs (Ljava/lang/String;)[Ljava/io/File;
D/dalvikvm( 3728): VFY: replacing opcode 0x6e at 0x000c
D/dalvikvm( 3728): DexOpt: couldn't find static field Landroid/os/Environment;.DIRECTORY_DOCUMENTS
W/dalvikvm( 3728): VFY: unable to resolve static field 110 (DIRECTORY_DOCUMENTS) in Landroid/os/Environment;
D/dalvikvm( 3728): VFY: replacing opcode 0x62 at 0x0052
D/AndroidRuntime( 3728): Shutting down VM
W/dalvikvm( 3728): threadid=1: thread exiting with uncaught exception (group=0x41c1d930)
--------- beginning of /dev/log/system
E/AndroidRuntime( 3728): FATAL EXCEPTION: main FATAL EXCEPTION (see previous post).

See fuller excerpt from Log in previous post.

**Comment by Nutomic** [comment]
Actually the same as #772, fixed in latest release.

**Comment by phil99** [comment]
@Nutomic 

It appears there is more than 1 issue here.
0.8.8 has indeed resolved the folder picker problem I was experiencing in 0.8.7, but crashes which cause a device reboot are still occurring regularly in a multitude of different scenarios, eg just when doing nothing, when editing a folder, when deleting a file etc. I cannot explain it, but as I said above, ST was rock solid up to, and including 0.8.4.

I have been unable to retrieve any sort of log after the device has rebooted.

**Comment by Nutomic** [comment]
Sorry I missed that part. However, an app should never cause your device to crash/reboot, unless something is wrong with your device/Android. And without a log there's no way to figure out what's happening.

**Comment by phil99** [comment]
@Nutomic 

Yes, I can appreciate that.
The only time my devices (more than one are showing this behaviour) crash & reboot in this way is when running ST, and only since 0.8.6
As there are no logs, I cannot shed any further light. If I do find some sort of pattern, or possibly a crash without reboot that gives me a log, I'll open a new issue.

**Comment by licaon-kter** [comment]
usb to PC, ADB logcat, make it crash, copy log from terminal?

**Comment by phil99** [comment]
@licaon-kter 

Thanks for the suggestion, but I don't have ADB installed on my elderly Windows XP laptop, and not sure I want to try. I'll look into it when I have some time.
