### ISSUE TITLE
Underlying Syncthing Stops Working After a few Minutes

### ISSUE THREAD

**Issue by snpalavan** [syncthing/syncthing-android#910]
A new issue introduced in this last version is that syncthing (not syncthing android) stops working after a few (5-10) min, including that the localhost website no longer functions and the folder info on ST android no longer functions. This has only started occurring after the latest update to STA v0.9.11. (i noted this in #870 at https://github.com/syncthing/syncthing-android/issues/870#issuecomment-309892678, but thought it warranted it's own issue)

Steps to produce:
Load STA on phone
Run underlying ST service
Wait 5-10 min
ST service no longer functioning

Once the ST service has stopped, the following things can be observed:
- The "view GUI" option no longer works and the missing page/unable to connect error is displayed
- The folder information within STA does not updated, including that it no longer says "scanning" or anything else, it is simply blank
- STA no longer syncs any information either direction

Here is an album of screenshots for what i describe:  http://imgur.com/a/v8Klu
I redacted information in pink so you could clearly note that the blanks everywhere were not from me :)

Restarting STA/ST gets it to work, but only briefly until the timeout occurs again.

### Version Information

    App Version: 0.9.11
    Syncthing Version: v0.14.30
    Android Version: Android 7.0 / Samsung Experience 8.1

Also, the log for ST simply says:
`--------- beginning of main`

Here is the log from STA (note the folder names are changed but i noted where they were the same via numbering - i only have two shared folders:  FLDR-ONE is on the internal storage and FLDR-TWO is on the SD card):
````--------- beginning of main
06-21 10:54:56.191 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/db/scan?folder=FLDR-ONE&sub=%2FAndroid%2Fdata%2Fcom.sec.android.gallery3d%2Fcache%2Flarge%2F-3666818439183210085.0.tmp failed: java.net.ConnectException: Connection refused
06-21 10:54:56.193 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:54:56.193 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:54:56.196 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:54:56.196 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:54:56.196 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/db/scan?folder=FLDR-ONE&sub=%2FAndroid%2Fdata%2Fcom.sec.android.gallery3d%2Fcache%2Fattribute%2F8269641534903458526.0.tmp failed: java.net.ConnectException: Connection refused
06-21 10:54:56.200 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:54:56.200 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:54:56.200 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:54:56.200 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:54:56.200 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/db/scan?folder=FLDR-ONE&sub=%2FAndroid%2Fdata%2Fcom.sec.android.gallery3d%2Fcache%2Fattribute%2F8269641534903458526.0 failed: java.net.ConnectException: Connection refused
06-21 10:54:56.203 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:54:56.203 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:54:56.207 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/db/scan?folder=FLDR-ONE&sub=%2FAndroid%2Fdata%2Fcom.sec.android.gallery3d%2Fcache%2Flarge%2F-3666818439183210085.0 failed: java.net.ConnectException: Connection refused
06-21 10:54:56.207 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/db/scan?folder=FLDR-ONE&sub=%2FAndroid%2Fdata%2Fcom.sec.android.gallery3d%2Fcache%2Fattribute%2F8269641534903458526.0.tmp failed: java.net.ConnectException: Connection refused
06-21 10:54:56.207 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/db/scan?folder=FLDR-ONE&sub=%2FAndroid%2Fdata%2Fcom.sec.android.gallery3d%2Fcache%2Flarge%2F-3666818439183210085.0.tmp failed: java.net.ConnectException: Connection refused
06-21 10:54:56.210 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:54:56.210 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:54:56.213 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/db/scan?folder=FLDR-ONE&sub=%2FAndroid%2Fdata%2Fcom.sec.android.gallery3d%2Fcache%2Flarge%2F-3666818439183210085.0 failed: java.net.ConnectException: Connection refused
06-21 10:54:56.220 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/db/scan?folder=FLDR-ONE&sub=%2FAndroid%2Fdata%2Fcom.sec.android.gallery3d%2Fcache%2Fattribute%2F8269641534903458526.0 failed: java.net.ConnectException: Connection refused
06-21 10:54:56.947 V/FolderObserver(10059): Received inotify event 100 at /Android/data/com.sec.android.gallery3d/cache/large/8213715993294335978.0.tmp
06-21 10:54:56.947 V/FolderObserver(10059): Received inotify event 40 at /Android/data/com.sec.android.gallery3d/cache/large/8213715993294335978.0.tmp
06-21 10:54:56.948 V/FolderObserver(10059): Received inotify event 80 at /Android/data/com.sec.android.gallery3d/cache/large/8213715993294335978.0
06-21 10:54:56.948 V/FolderObserver(10059): Received inotify event 8 at /Android/data/com.sec.android.gallery3d/cache/large/8213715993294335978.0
06-21 10:54:56.948 V/FolderObserver(10059): Received inotify event 100 at /Android/data/com.sec.android.gallery3d/cache/attribute/-3592878499077186385.0.tmp
06-21 10:54:56.949 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:54:56.949 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:54:56.949 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:54:56.949 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:54:56.951 V/FolderObserver(10059): Received inotify event 40 at /Android/data/com.sec.android.gallery3d/cache/attribute/-3592878499077186385.0.tmp
06-21 10:54:56.951 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/db/scan?folder=FLDR-ONE&sub=%2FAndroid%2Fdata%2Fcom.sec.android.gallery3d%2Fcache%2Flarge%2F8213715993294335978.0.tmp failed: java.net.ConnectException: Connection refused
06-21 10:54:56.952 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:54:56.952 V/FolderObserver(10059): Received inotify event 80 at /Android/data/com.sec.android.gallery3d/cache/attribute/-3592878499077186385.0
06-21 10:54:56.952 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:54:56.952 V/FolderObserver(10059): Received inotify event 8 at /Android/data/com.sec.android.gallery3d/cache/attribute/-3592878499077186385.0
06-21 10:54:56.952 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/db/scan?folder=FLDR-ONE&sub=%2FAndroid%2Fdata%2Fcom.sec.android.gallery3d%2Fcache%2Flarge%2F8213715993294335978.0 failed: java.net.ConnectException: Connection refused
06-21 10:54:56.954 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:54:56.954 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:54:56.954 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:54:56.954 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:54:56.954 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:54:56.954 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:54:56.956 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/db/scan?folder=FLDR-ONE&sub=%2FAndroid%2Fdata%2Fcom.sec.android.gallery3d%2Fcache%2Fattribute%2F-3592878499077186385.0.tmp failed: java.net.ConnectException: Connection refused
06-21 10:54:56.956 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/db/scan?folder=FLDR-ONE&sub=%2FAndroid%2Fdata%2Fcom.sec.android.gallery3d%2Fcache%2Flarge%2F8213715993294335978.0.tmp failed: java.net.ConnectException: Connection refused
06-21 10:54:56.956 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/db/scan?folder=FLDR-ONE&sub=%2FAndroid%2Fdata%2Fcom.sec.android.gallery3d%2Fcache%2Flarge%2F8213715993294335978.0 failed: java.net.ConnectException: Connection refused
06-21 10:54:56.956 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:54:56.957 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:54:56.957 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/db/scan?folder=FLDR-ONE&sub=%2FAndroid%2Fdata%2Fcom.sec.android.gallery3d%2Fcache%2Fattribute%2F-3592878499077186385.0 failed: java.net.ConnectException: Connection refused
06-21 10:54:56.958 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:54:56.958 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:54:56.958 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/db/scan?folder=FLDR-ONE&sub=%2FAndroid%2Fdata%2Fcom.sec.android.gallery3d%2Fcache%2Fattribute%2F-3592878499077186385.0.tmp failed: java.net.ConnectException: Connection refused
06-21 10:54:56.959 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/db/scan?folder=FLDR-ONE&sub=%2FAndroid%2Fdata%2Fcom.sec.android.gallery3d%2Fcache%2Fattribute%2F-3592878499077186385.0 failed: java.net.ConnectException: Connection refused
06-21 10:54:57.052 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:54:57.052 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:54:57.052 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:54:57.053 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:54:57.054 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/system/status failed: java.net.ConnectException: Connection refused
06-21 10:54:57.056 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:54:57.056 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:54:57.057 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/system/version failed: java.net.ConnectException: Connection refused
06-21 10:54:57.060 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/system/connections failed: java.net.ConnectException: Connection refused
06-21 10:55:02.054 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:02.054 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:02.054 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:02.054 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:02.055 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:02.055 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:02.059 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/system/status failed: java.net.ConnectException: Connection refused
06-21 10:55:02.059 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/system/version failed: java.net.ConnectException: Connection refused
06-21 10:55:02.060 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/system/connections failed: java.net.ConnectException: Connection refused
06-21 10:55:06.210 V/FolderObserver(10059): Received inotify event 100 at /.face/.EventSync/Event_Cloud_DownSync_1498060506209.txt
06-21 10:55:06.210 V/FolderObserver(10059): Received inotify event 8 at /.face/.EventSync/Event_Cloud_DownSync_1498060506209.txt
06-21 10:55:06.211 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:06.211 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:06.212 V/FolderObserver(10059): Received inotify event 200 at /.face/.EventSync/Event_Cloud_DownSync_1498060506209.txt
06-21 10:55:06.214 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/db/scan?folder=FLDR-ONE&sub=%2F.face%2F.EventSync%2FEvent_Cloud_DownSync_1498060506209.txt failed: java.net.ConnectException: Connection refused
06-21 10:55:06.215 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:06.215 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:06.215 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:06.215 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:06.217 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/db/scan?folder=FLDR-ONE&sub=%2F.face%2F.EventSync%2FEvent_Cloud_DownSync_1498060506209.txt failed: java.net.ConnectException: Connection refused
06-21 10:55:06.217 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/db/scan?folder=FLDR-ONE&sub=%2F.face%2F.EventSync%2FEvent_Cloud_DownSync_1498060506209.txt failed: java.net.ConnectException: Connection refused
06-21 10:55:07.053 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:07.053 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:07.055 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:07.055 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:07.060 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/system/status failed: java.net.ConnectException: Connection refused
06-21 10:55:07.061 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:07.061 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:07.066 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/system/connections failed: java.net.ConnectException: Connection refused
06-21 10:55:07.080 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/system/version failed: java.net.ConnectException: Connection refused
06-21 10:55:10.165 V/FolderObserver(10059): Received inotify event 100 at /.face/.EventSync/Event_Cloud_DownSync_1498060510162.txt
06-21 10:55:10.165 V/FolderObserver(10059): Received inotify event 8 at /.face/.EventSync/Event_Cloud_DownSync_1498060510162.txt
06-21 10:55:10.165 V/FolderObserver(10059): Received inotify event 200 at /.face/.EventSync/Event_Cloud_DownSync_1498060510162.txt
06-21 10:55:10.170 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:10.171 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:10.175 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/db/scan?folder=FLDR-ONE&sub=%2F.face%2F.EventSync%2FEvent_Cloud_DownSync_1498060510162.txt failed: java.net.ConnectException: Connection refused
06-21 10:55:10.179 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:10.179 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:10.182 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/db/scan?folder=FLDR-ONE&sub=%2F.face%2F.EventSync%2FEvent_Cloud_DownSync_1498060510162.txt failed: java.net.ConnectException: Connection refused
06-21 10:55:10.182 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:10.183 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:10.190 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/db/scan?folder=FLDR-ONE&sub=%2F.face%2F.EventSync%2FEvent_Cloud_DownSync_1498060510162.txt failed: java.net.ConnectException: Connection refused
06-21 10:55:12.053 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:12.053 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:12.056 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/system/status failed: java.net.ConnectException: Connection refused
06-21 10:55:12.056 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:12.056 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:12.057 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:12.058 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:12.059 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/system/version failed: java.net.ConnectException: Connection refused
06-21 10:55:12.061 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/system/connections failed: java.net.ConnectException: Connection refused
06-21 10:55:13.313 V/FolderObserver(10059): Received inotify event 8 at /Android/data/com.sec.android.gallery3d/cache/large/journal
06-21 10:55:13.315 V/FolderObserver(10059): Received inotify event 8 at /Android/data/com.sec.android.gallery3d/cache/attribute/journal
06-21 10:55:13.315 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:13.315 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:13.317 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:13.318 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:13.321 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/db/scan?folder=FLDR-ONE&sub=%2FAndroid%2Fdata%2Fcom.sec.android.gallery3d%2Fcache%2Fattribute%2Fjournal failed: java.net.ConnectException: Connection refused
06-21 10:55:13.326 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/db/scan?folder=FLDR-ONE&sub=%2FAndroid%2Fdata%2Fcom.sec.android.gallery3d%2Fcache%2Flarge%2Fjournal failed: java.net.ConnectException: Connection refused
06-21 10:55:13.475 D/ViewRootImpl@608ca0d[SettingsActivity](10059): mHardwareRenderer.destroy()#1
06-21 10:55:13.479 D/ViewRootImpl@608ca0d[SettingsActivity](10059): Relayout returned: oldFrame=[0,0][1440,2960] newFrame=[0,0][1440,2960] result=0x1 surface={isValid=false 0} surfaceGenerationChanged=false
06-21 10:55:13.569 D/ViewRootImpl@608ca0d[SettingsActivity](10059): Relayout returned: oldFrame=[0,0][1440,2960] newFrame=[0,0][1440,2960] result=0x3 surface={isValid=true 547108651008} surfaceGenerationChanged=true
06-21 10:55:13.569 D/ViewRootImpl@608ca0d[SettingsActivity](10059): mHardwareRenderer.initialize() mSurface={isValid=true 547108651008} hwInitialized=true
06-21 10:55:13.607 D/ViewRootImpl@608ca0d[SettingsActivity](10059): MSG_WINDOW_FOCUS_CHANGED 1
06-21 10:55:13.607 D/ViewRootImpl@608ca0d[SettingsActivity](10059): mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true 547108651008}
06-21 10:55:13.614 V/InputMethodManager(10059): Starting input: tba=android.view.inputmethod.EditorInfo@e2828f4 nm : com.nutomic.syncthingandroid ic=null
06-21 10:55:13.614 I/InputMethodManager(10059): [IMM] startInputInner - mService.startInputOrWindowGainedFocus
06-21 10:55:13.618 D/InputTransport(10059): Input channel constructed: fd=115
06-21 10:55:14.873 D/ViewRootImpl@608ca0d[SettingsActivity](10059): ViewPostImeInputStage processKey 0
06-21 10:55:14.962 D/ViewRootImpl@608ca0d[SettingsActivity](10059): ViewPostImeInputStage processKey 1
06-21 10:55:15.047 D/ViewRootImpl@9df0706[MainActivity](10059): Relayout returned: oldFrame=[0,0][1440,2960] newFrame=[0,0][1440,2960] result=0x7 surface={isValid=true 547749209600} surfaceGenerationChanged=true
06-21 10:55:15.047 D/ViewRootImpl@9df0706[MainActivity](10059): mHardwareRenderer.initialize() mSurface={isValid=true 547749209600} hwInitialized=true
06-21 10:55:15.140 D/ViewRootImpl@9df0706[MainActivity](10059): MSG_WINDOW_FOCUS_CHANGED 1
06-21 10:55:15.140 D/ViewRootImpl@9df0706[MainActivity](10059): mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true 547749209600}
06-21 10:55:15.142 V/InputMethodManager(10059): Starting input: tba=android.view.inputmethod.EditorInfo@d5faa92 nm : com.nutomic.syncthingandroid ic=null
06-21 10:55:15.142 I/InputMethodManager(10059): [IMM] startInputInner - mService.startInputOrWindowGainedFocus
06-21 10:55:15.175 D/InputTransport(10059): Input channel constructed: fd=116
06-21 10:55:15.175 D/InputTransport(10059): Input channel destroyed: fd=115
06-21 10:55:15.191 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:15.192 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:15.201 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:15.201 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:15.204 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:15.204 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:15.228 D/ViewRootImpl@608ca0d[SettingsActivity](10059): mHardwareRenderer.destroy()#1
06-21 10:55:15.232 D/ViewRootImpl@608ca0d[SettingsActivity](10059): Relayout returned: oldFrame=[0,0][1440,2960] newFrame=[0,0][1440,2960] result=0x5 surface={isValid=false 0} surfaceGenerationChanged=true
06-21 10:55:15.232 D/ViewRootImpl@608ca0d[SettingsActivity](10059): MSG_WINDOW_FOCUS_CHANGED 0
06-21 10:55:15.233 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/system/connections failed: java.net.ConnectException: Connection refused
06-21 10:55:15.233 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/db/status?folder=FLDR-TWO failed: java.net.ConnectException: Connection refused
06-21 10:55:15.233 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/db/status?folder=FLDR-ONE failed: java.net.ConnectException: Connection refused
06-21 10:55:15.234 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:15.234 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:15.234 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:15.234 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:15.234 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:15.234 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:15.236 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/system/connections failed: java.net.ConnectException: Connection refused
06-21 10:55:15.237 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:15.237 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:15.238 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/system/connections failed: java.net.ConnectException: Connection refused
06-21 10:55:15.238 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/system/connections failed: java.net.ConnectException: Connection refused
06-21 10:55:15.239 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:15.239 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:15.239 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:15.239 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:15.239 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/system/connections failed: java.net.ConnectException: Connection refused
06-21 10:55:15.240 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:15.240 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:15.240 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/system/connections failed: java.net.ConnectException: Connection refused
06-21 10:55:15.241 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:15.241 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:15.241 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:15.241 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:15.241 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/system/connections failed: java.net.ConnectException: Connection refused
06-21 10:55:15.241 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:15.241 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:15.242 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/system/connections failed: java.net.ConnectException: Connection refused
06-21 10:55:15.243 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/system/connections failed: java.net.ConnectException: Connection refused
06-21 10:55:15.243 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/system/connections failed: java.net.ConnectException: Connection refused
06-21 10:55:15.243 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/system/connections failed: java.net.ConnectException: Connection refused
06-21 10:55:15.615 D/ViewRootImpl@608ca0d[SettingsActivity](10059): mHardwareRenderer.destroy()#4
06-21 10:55:15.615 D/ViewRootImpl@608ca0d[SettingsActivity](10059): dispatchDetachedFromWindow
06-21 10:55:15.631 D/InputTransport(10059): Input channel destroyed: fd=113
06-21 10:55:15.638 I/SemDesktopModeManager(10059): unregisterListener: android.view.ViewRootImpl$3@8ce4ca4
06-21 10:55:15.968 D/ViewRootImpl@9df0706[MainActivity](10059): ViewPostImeInputStage processPointer 0
06-21 10:55:16.033 D/ViewRootImpl@9df0706[MainActivity](10059): ViewPostImeInputStage processPointer 1
06-21 10:55:16.487 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:16.487 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:16.487 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:16.487 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:16.487 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:16.488 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:16.501 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/system/version failed: java.net.ConnectException: Connection refused
06-21 10:55:16.501 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/system/status failed: java.net.ConnectException: Connection refused
06-21 10:55:16.501 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/system/connections failed: java.net.ConnectException: Connection refused
06-21 10:55:17.605 D/ViewRootImpl@9df0706[MainActivity](10059): ViewPostImeInputStage processPointer 0
06-21 10:55:17.671 D/ViewRootImpl@9df0706[MainActivity](10059): ViewPostImeInputStage processPointer 1
06-21 10:55:17.711 D/ViewRootImpl@9df0706[MainActivity](10059): MSG_WINDOW_FOCUS_CHANGED 0
--------- beginning of system
06-21 10:55:17.732 V/ActivityThread(10059): performLaunchActivity: mActivityCurrentConfig={0 1.0 themeSeq = 0 showBtnBg = 0 310mcc260mnc [en_US] ldltr sw411dp w411dp h773dp 560dpi nrml long port ?dc finger -keyb/v/h -nav/h mkbd/h desktop/d s.14}
06-21 10:55:17.758 D/AbsListView(10059): Get MotionRecognitionManager
06-21 10:55:17.758 D/MotionRecognitionManager(10059): mSContextService = com.samsung.android.hardware.context.ISemContextService$Stub$Proxy@97cbb4c
06-21 10:55:17.759 D/MotionRecognitionManager(10059): motionService = com.samsung.android.gesture.IMotionRecognitionService$Stub$Proxy@3f51795
06-21 10:55:17.759 D/MotionRecognitionManager(10059): motionService = com.samsung.android.gesture.IMotionRecognitionService$Stub$Proxy@3f51795
06-21 10:55:17.787 I/SemDesktopModeManager(10059): registerListener: android.view.ViewRootImpl$3@e53bba
06-21 10:55:17.789 D/ViewRootImpl@5a94a6b[SettingsActivity](10059): ThreadedRenderer.create() translucent=false
06-21 10:55:17.792 D/InputTransport(10059): Input channel constructed: fd=115
06-21 10:55:17.794 D/ViewRootImpl@5a94a6b[SettingsActivity](10059): setView = DecorView@78379c8[SettingsActivity] touchMode=true
06-21 10:55:17.799 D/ViewRootImpl@5a94a6b[SettingsActivity](10059): dispatchAttachedToWindow
06-21 10:55:17.830 D/ViewRootImpl@5a94a6b[SettingsActivity](10059): Relayout returned: oldFrame=[0,0][0,0] newFrame=[0,0][1440,2960] result=0x27 surface={isValid=true 547108651008} surfaceGenerationChanged=true
06-21 10:55:17.831 D/ViewRootImpl@5a94a6b[SettingsActivity](10059): mHardwareRenderer.initialize() mSurface={isValid=true 547108651008} hwInitialized=true
06-21 10:55:17.842 D/AbsListView(10059):  onsize change 
06-21 10:55:17.846 D/DeviceStateHolder(10059): All SSIDs allowed for syncing
06-21 10:55:17.896 D/ViewRootImpl@5a94a6b[SettingsActivity](10059): MSG_RESIZED_REPORT: frame=Rect(0, 0 - 1440, 2960) ci=Rect(0, 84 - 0, 168) vi=Rect(0, 84 - 0, 168) or=1
06-21 10:55:17.896 D/ViewRootImpl@5a94a6b[SettingsActivity](10059): MSG_WINDOW_FOCUS_CHANGED 1
06-21 10:55:17.896 D/ViewRootImpl@5a94a6b[SettingsActivity](10059): mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true 547108651008}
06-21 10:55:17.897 V/InputMethodManager(10059): Starting input: tba=android.view.inputmethod.EditorInfo@76627b3 nm : com.nutomic.syncthingandroid ic=null
06-21 10:55:17.898 I/InputMethodManager(10059): [IMM] startInputInner - mService.startInputOrWindowGainedFocus
06-21 10:55:17.907 D/InputTransport(10059): Input channel constructed: fd=113
06-21 10:55:17.907 D/InputTransport(10059): Input channel destroyed: fd=116
06-21 10:55:17.937 D/OpenGLRenderer(10059): endAllActiveAnimators on 0x7f684ed400 (RippleDrawable) with handle 0x7f64d48c20
06-21 10:55:17.937 D/ViewRootImpl@9df0706[MainActivity](10059): mHardwareRenderer.destroy()#1
06-21 10:55:17.945 D/ViewRootImpl@9df0706[MainActivity](10059): Relayout returned: oldFrame=[0,0][1440,2960] newFrame=[0,0][1440,2960] result=0x5 surface={isValid=false 0} surfaceGenerationChanged=true
06-21 10:55:18.349 D/ViewRootImpl@9df0706[MainActivity](10059): Relayout returned: oldFrame=[0,0][1440,2960] newFrame=[0,0][1440,2960] result=0x5 surface={isValid=false 0} surfaceGenerationChanged=false
06-21 10:55:19.087 D/ViewRootImpl@5a94a6b[SettingsActivity](10059): ViewPostImeInputStage processPointer 0
06-21 10:55:19.158 D/ViewRootImpl@5a94a6b[SettingsActivity](10059): ViewPostImeInputStage processPointer 1
06-21 10:55:19.159 D/AbsListView(10059): onTouchUp() mTouchMode : 0
06-21 10:55:19.228 D/AbsListView(10059): Get MotionRecognitionManager
06-21 10:55:19.251 I/SemDesktopModeManager(10059): registerListener: android.view.ViewRootImpl$3@59f7ace
06-21 10:55:19.255 D/ViewRootImpl@5a63def[Debug](10059): ThreadedRenderer.create() translucent=false
06-21 10:55:19.264 D/InputTransport(10059): Input channel constructed: fd=116
06-21 10:55:19.266 D/ViewRootImpl@5a63def[Debug](10059): setView = DecorView@48160fc[Debug] touchMode=true
06-21 10:55:19.270 D/ViewRootImpl@5a63def[Debug](10059): dispatchAttachedToWindow
06-21 10:55:19.305 D/ViewRootImpl@5a63def[Debug](10059): Relayout returned: oldFrame=[0,0][0,0] newFrame=[0,0][1440,2960] result=0x27 surface={isValid=true 547749209600} surfaceGenerationChanged=true
06-21 10:55:19.305 D/ViewRootImpl@5a63def[Debug](10059): mHardwareRenderer.initialize() mSurface={isValid=true 547749209600} hwInitialized=true
06-21 10:55:19.352 D/AbsListView(10059):  onsize change 
06-21 10:55:19.355 D/ViewRootImpl@5a63def[Debug](10059): MSG_WINDOW_FOCUS_CHANGED 1
06-21 10:55:19.355 D/ViewRootImpl@5a63def[Debug](10059): mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true 547749209600}
06-21 10:55:19.357 V/InputMethodManager(10059): Starting input: tba=android.view.inputmethod.EditorInfo@b8dbd62 nm : com.nutomic.syncthingandroid ic=null
06-21 10:55:19.357 I/InputMethodManager(10059): [IMM] startInputInner - mService.startInputOrWindowGainedFocus
06-21 10:55:19.358 D/InputTransport(10059): Input channel constructed: fd=122
06-21 10:55:19.358 D/InputTransport(10059): Input channel destroyed: fd=113
06-21 10:55:19.379 D/ViewRootImpl@5a63def[Debug](10059): MSG_RESIZED_REPORT: frame=Rect(0, 0 - 1440, 2960) ci=Rect(0, 84 - 0, 168) vi=Rect(0, 84 - 0, 168) or=1
06-21 10:55:19.395 D/ViewRootImpl@5a94a6b[SettingsActivity](10059): MSG_WINDOW_FOCUS_CHANGED 0
06-21 10:55:20.176 V/FolderObserver(10059): Received inotify event 100 at /.face/.EventSync/Event_Cloud_DownSync_1498060520172.txt
06-21 10:55:20.176 V/FolderObserver(10059): Received inotify event 8 at /.face/.EventSync/Event_Cloud_DownSync_1498060520172.txt
06-21 10:55:20.176 V/FolderObserver(10059): Received inotify event 200 at /.face/.EventSync/Event_Cloud_DownSync_1498060520172.txt
06-21 10:55:20.178 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:20.178 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:20.181 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/db/scan?folder=FLDR-ONE&sub=%2F.face%2F.EventSync%2FEvent_Cloud_DownSync_1498060520172.txt failed: java.net.ConnectException: Connection refused
06-21 10:55:20.182 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:20.182 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:20.182 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:20.183 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:20.186 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/db/scan?folder=FLDR-ONE&sub=%2F.face%2F.EventSync%2FEvent_Cloud_DownSync_1498060520172.txt failed: java.net.ConnectException: Connection refused
06-21 10:55:20.186 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/db/scan?folder=FLDR-ONE&sub=%2F.face%2F.EventSync%2FEvent_Cloud_DownSync_1498060520172.txt failed: java.net.ConnectException: Connection refused
06-21 10:55:21.488 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:21.488 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:21.489 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:21.489 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:21.489 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:21.489 I/System.out(10059): (HTTPLog)-Static: isSBSettingEnabled false
06-21 10:55:21.492 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/system/status failed: java.net.ConnectException: Connection refused
06-21 10:55:21.492 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/system/connections failed: java.net.ConnectException: Connection refused
06-21 10:55:21.492 W/ApiRequest(10059): Request to https://127.0.0.1:8384/rest/system/version failed: java.net.ConnectException: Connection refused
06-21 10:55:21.550 D/ViewRootImpl@5a63def[Debug](10059): ViewPostImeInputStage processPointer 0
06-21 10:55:21.650 D/ViewRootImpl@5a63def[Debug](10059): ViewPostImeInputStage processPointer 1
06-21 10:55:21.651 D/AbsListView(10059): onTouchUp() mTouchMode : 0
06-21 10:55:21.746 D/ViewRootImpl@5a63def[Debug](10059): MSG_WINDOW_FOCUS_CHANGED 0
06-21 10:55:21.773 V/ActivityThread(10059): performLaunchActivity: mActivityCurrentConfig={0 1.0 themeSeq = 0 showBtnBg = 0 310mcc260mnc [en_US] ldltr sw411dp w411dp h773dp 560dpi nrml long port ?dc finger -keyb/v/h -nav/h mkbd/h desktop/d s.14}
06-21 10:55:21.798 I/SemDesktopModeManager(10059): registerListener: android.view.ViewRootImpl$3@8fcbb3c
06-21 10:55:21.800 D/ViewRootImpl@1efa1a[LogActivity](10059): ThreadedRenderer.create() translucent=false
06-21 10:55:21.804 D/InputTransport(10059): Input channel constructed: fd=132
06-21 10:55:21.806 D/ViewRootImpl@1efa1a[LogActivity](10059): setView = DecorView@780994b[LogActivity] touchMode=true
06-21 10:55:21.808 D/DeviceStateHolder(10059): All SSIDs allowed for syncing
06-21 10:55:21.815 D/ViewRootImpl@1efa1a[LogActivity](10059): dispatchAttachedToWindow
06-21 10:55:21.839 D/ViewRootImpl@1efa1a[LogActivity](10059): Relayout returned: oldFrame=[0,0][0,0] newFrame=[0,0][1440,2960] result=0x27 surface={isValid=true 547108654592} surfaceGenerationChanged=true
06-21 10:55:21.840 D/ViewRootImpl@1efa1a[LogActivity](10059): mHardwareRenderer.initialize() mSurface={isValid=true 547108654592} hwInitialized=true
06-21 10:55:21.855 D/ScrollView(10059):  onsize change changed 
06-21 10:55:21.912 D/ViewRootImpl@1efa1a[LogActivity](10059): MSG_RESIZED_REPORT: frame=Rect(0, 0 - 1440, 2960) ci=Rect(0, 84 - 0, 168) vi=Rect(0, 84 - 0, 168) or=1
06-21 10:55:21.912 D/ViewRootImpl@1efa1a[LogActivity](10059): MSG_WINDOW_FOCUS_CHANGED 1
06-21 10:55:21.912 D/ViewRootImpl@1efa1a[LogActivity](10059): mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true 547108654592}
06-21 10:55:21.913 V/InputMethodManager(10059): Starting input: tba=android.view.inputmethod.EditorInfo@b310fcc nm : com.nutomic.syncthingandroid ic=null
06-21 10:55:21.913 I/InputMethodManager(10059): [IMM] startInputInner - mService.startInputOrWindowGainedFocus
06-21 10:55:21.922 D/InputTransport(10059): Input channel constructed: fd=113
06-21 10:55:21.922 D/InputTransport(10059): Input channel destroyed: fd=122
06-21 10:55:21.968 D/OpenGLRenderer(10059): endAllActiveAnimators on 0x7f658b9c00 (ListView) with handle 0x7f64d48a80
06-21 10:55:21.968 D/ViewRootImpl@5a63def[Debug](10059): mHardwareRenderer.destroy()#1
06-21 10:55:21.973 D/ViewRootImpl@5a63def[Debug](10059): Relayout returned: oldFrame=[0,0][1440,2960] newFrame=[0,0][1440,2960] result=0x5 surface={isValid=false 0} surfaceGenerationChanged=true
06-21 10:55:21.978 D/ViewRootImpl@5a94a6b[SettingsActivity](10059): mHardwareRenderer.destroy()#1
06-21 10:55:21.982 D/ViewRootImpl@5a94a6b[SettingsActivity](10059): Relayout returned: oldFrame=[0,0][1440,2960] newFrame=[0,0][1440,2960] result=0x5 surface={isValid=false 0} surfaceGenerationChanged=true
06-21 10:55:22.358 D/ViewRootImpl@5a94a6b[SettingsActivity](10059): Relayout returned: oldFrame=[0,0][1440,2960] newFrame=[0,0][1440,2960] result=0x5 surface={isValid=false 0} surfaceGenerationChanged=false
06-21 10:55:23.004 D/ViewRootImpl@1efa1a[LogActivity](10059): ViewPostImeInputStage processPointer 0
06-21 10:55:23.237 D/ViewRootImpl@1efa1a[LogActivity](10059): ViewPostImeInputStage processPointer 1
06-21 10:55:23.357 D/ViewRootImpl@1efa1a[LogActivity](10059): ViewPostImeInputStage processPointer 0
06-21 10:55:23.855 D/ViewRootImpl@1efa1a[LogActivity](10059): ViewPostImeInputStage processPointer 1
06-21 10:55:24.040 D/ViewRootImpl@1efa1a[LogActivity](10059): ViewPostImeInputStage processPointer 0
06-21 10:55:24.303 D/ViewRootImpl@1efa1a[LogActivity](10059): ViewPostImeInputStage processPointer 1
06-21 10:55:25.944 D/ViewRootImpl@1efa1a[LogActivity](10059): ViewPostImeInputStage processPointer 0
06-21 10:55:26.045 D/ViewRootImpl@1efa1a[LogActivity](10059): ViewPostImeInputStage processPointer 1````

**Comment by jmintb** [comment]
I can't access the album. Are you using file versioning?

**Comment by snpalavan** [comment]
@jmintb hmm odd that you couldn't see the album! I double checked it is on public and then toggled it. see if it works now :)

As for file versioning, no i am not using file versioning on my phone, only on i think 2 of the connected devices

**Comment by jmintb** [comment]
I just get a 404 when opening the album. Syncthing is running fine on my phone: Moto g3 android 6. Have you always used your sd card? :)

**Comment by snpalavan** [comment]
@jmintb ahh, it's some weird issue with github translation, just copy/paste the link URL and it will work...not sure why it doesnt lol

and yeah i've been doing it with these same folders since the first release of STA! And everything was working fine (except the respecting wi-fi condition issue that is a separate one) until this last update. Literally, it updated one night, then the next day i wake up and it's just doing this :/

**Comment by wweich** [comment]
The markdown syntax for the link is wrong. The url is "url" while the label is http://imgur.com/a/v8Klu.

I'm running Syncthing on my Pixel without any problems. I'm using the "keep cpu awake" feature since it's introduction. And of course Syncthing is set to "no power optimization" in the Android system settings.

When was your last Android Update / device switch?

**Comment by snpalavan** [comment]
@wweich Whoooops, ok fixed it! How embarrassing haha

And yeah i have those features enabled as well, and STA is not on any power saving list or other memory saving list (technically i just dont have any app like this, but the idea is the same)

The last update I had was at least 2-3 weeks ago. I don't remember exact timeline, but I know for sure that the last phone update I had was at least a week prior to the at-issue version of STA, and everything was working fine under the phone update (again, see caveat), but stopped after the STA update.

**Comment by jmintb** [comment]
@AudriusButkevicius  Why did you close it? :)

**Comment by AudriusButkevicius** [comment]
Sorry, I understood from the comment by @snpalavan that it was a "battery not optimized" problem, and it was fixed.

**Comment by snpalavan** [comment]
@AudriusButkevicius 
oh! Sorry about the confusion! the "fixed it" was referring to the URL issue :P

The actual issue with the app is not fixed though :/

**Comment by DrSchnagels** [comment]
Same problem with my phone:
Android 7.1.1, OnePlus 5. Even with STA set to not battery optimized, the service shuts down at 10 minutes after the display is off.
I had the same problem with my Nexus 6P and in some boards I read that the problem is, that I'm exclusively connected to 5 GHz networks. Both phones seem to do something to the wifi connection on the 5 GHz network.
At work where I have an old 2.4 GHz router, the phone's STA stays perfectly stable and always connected.

Maybe this helps? Maybe we need a 5 GHz network ping to keep up the connections to other pc's syncthing instances.

**Comment by jmintb** [comment]
@AudriusButkevicius Are you on a 5Ghz wifi connection?

**Comment by AudriusButkevicius** [comment]
I don't actually use syncthing on the phone, sorry.

**Comment by jmintb** [comment]
Ups sry, I ment to ask @snpalavan :). 
@snpalavan Do you use 5Ghz or 2.4GHz?

**Comment by snpalavan** [comment]
@jmintb 

I use both, but, at least for me, it occurs on either

**Comment by jebeld17** [comment]
Is this similar to #922?

**Comment by snpalavan** [comment]
@jebeld17 Without knowing exact specifics of that case, my thought is no. The issue described here is that, while ST will initially start and work for a few minutes, after that time it simply fails to allow connections, and shows an HTTPS connection error when you choose ST GUI.

**Comment by snpalavan** [comment]
Ok so I finally got the syncthing log to fill in, and it looks like the underlying issue here is a corrupt data-block causing a panic:

`panic: leveldb/table: corruption on data-block (pos=1327081): checksum mismatch, want=0x88ff8888 got=0xbc15da5d [file=002647.ldb]
	panic: runtime error: invalid memory address or nil pointer dereference	panic: leveldb/table: corruption on data-block (pos=1327081): checksum mismatch, want=0x88ff8888 got=0xbc15da5d [file=002647.ldb]
`

The weird part is, this SAME thing occurs even after I select reset database. I'm going to try clearing data and setting up everything from scratch to see if i still get this issue.

**Comment by acolomb** [comment]
See https://github.com/syncthing/syncthing-android/issues/368#issuecomment-322026572 for a possible workaround that keeps Syncthing running in the background for longer periods of time.

**Comment by snpalavan** [comment]
@Nutomic @acolomb 
So after I just uninstalled, cleared data, and reinstalled, it seems to be working fine. So it looks like the original _specific_ issue I was having is now fixed. However, the fact that resetting the database via STA apparently did not solve a checksum mismatch/nil pointer error when it should be reindexing the whole thing is interesting. If you guys need/want any more info just let me know!

Also, again, while I think the _specific_ issue originally experienced is "resolved," the underlying issue of why resetting the db still leaves data-block corruption is possibly still an issue. So, I'll leave it to you guys whether you want to close this issue as solved.

**Comment by meersjo** [comment]
Same issue here; after trying the power saving and keep cpu alive options; I saved config; uninstalled (from FreeDroid) and reinstalled (one minor higher from Play store); now also works again as expected.

I did note that "show logs" consistently showed an empty log on the phone.

**Comment by Catfriend1** [comment]
@snpalavan  @meersjo As I understand your comments, the issue got resolved.
